### PR TITLE
Added Drink-Water Project

### PR DESCRIPTION
**Pull request by itsmohitnamdeo**
### 👨‍💻 Changes proposed

Added Drink-Water Project

### ✅ Check List
- [ ] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [ ] This PR does not contain plagiarized content.
- [ ] My Addition/Changes works properly and matches the overall repo pattern.
- [ ] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Drink-Water

### CODE REVIEW

**Comment by NOiR-07** [comment]
Add your project in the index of the website too

**Comment by itsmohitnamdeo** [comment]
Project Demo
Drink-Water

**Comment by NOiR-07** [comment]
update your forked repo to resolve the conflicts

**Comment by NOiR-07** [comment]
don't make any changes in index file, just add your project code there

**Comment by itsmohitnamdeo** [comment]
> don't make any changes in index file, just add your project code there

I already added the code

**Pull request closed without merging**
