### PR TITLE
Added flappy bird game

### PR DESCRIPTION
**Pull request by pranjay-poddar**
### 👨‍💻 Changes proposed
Added a Flappy Bird game in HTML CSS and JS

### ✅ Check List (Check all the applicable boxes) 

- [X] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [X] This PR does not contain plagiarized content.
- [X] My Addition/Changes works properly and matches the overall repo pattern.
- [X] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

flappybird

### CODE REVIEW

**Comment by pranjay-poddar** [comment]
@Astrodevil please review my PR

**Comment by pranjay-poddar** [comment]
@Astrodevil please review and merge my PR

**Comment by pranjay-poddar** [comment]
@sreelakshmig009 @Astrodevil can anyone of project maintainer please review my PR so that I can proceed with other issues.

**Review by Astrodevil — COMMENTED** [review]
looks good

**Pull request merged**
