### PR TITLE
Added CRUD Project files

### LINKED ISSUE #328: Add a new CRUD Project
A CRUD Project basically means Create , Read , Update and Delete where users can store and modify their data.
Tech stacks used :  HTML , CSS and Javascript.
It is absolutely responsive as well as minimal UI that users can switch between light and dark mode.
<br>
Screenshot (630)

### PR DESCRIPTION
**Pull request by MannyP31**
### 🛠️ Fixes Issue (Number)

Closes #328 

### 👨‍💻 Changes proposed

I added a new CRUD Project made with JS .

### ✅ Check List (Check all the applicable boxes) 
- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

This is a CRUD Project made with Javascript . It stands for Create , Read , Update and Delete .It helps the users to enter and modify their data according to their needs.Kindly let me know if it is alright or I need to work on that to make other necessary changes.

### 📷 Screenshots

Screenshot (630)

### CODE REVIEW

**Review by Palaksharma23 — CHANGES_REQUESTED** [review]
please change your CSS path to href="/assets/css/crud-project.css"
and JS path to src="/assets/Js/crud-project.js" :)

**Comment by MannyP31** [comment]
> please change your CSS path to href="/assets/css/crud-project.css" and JS path to src="/assets/Js/crud-project.js" :)

@Palaksharma23 I have made the suggested changes at their respective places. Kindly verify that and merge the PR !! 😊👍

**Comment by NOiR-07** [comment]
add your project in the index file of the website too

**Comment by MannyP31** [comment]
> add your project in the index file of the website too

Will you plz elaborate it a bit @NOiR-07

**Comment by Palaksharma23** [comment]
>> Will you plz elaborate it a bit @NOiR-07

@MannyP31 there is an index.html file in the codebase kindly add your project in that file so that it can show up on the website

**Comment by MannyP31** [comment]
> > > Will you plz elaborate it a bit @NOiR-07
> 
> @MannyP31 there is an index.html file in the codebase kindly add your project in that file so that it can show up on the website

I have made the necessary changes as suggested . Please go through it once ! @Palaksharma23

**Review by Palaksharma23 — APPROVED** [review]

**Pull request merged**
