### PR TITLE
Added Moving Car Animation

### LINKED ISSUE #629: Moving car animation effect
I have created a moving car animation effect. I want to add it. Please assign it to me.

### PR DESCRIPTION
**Pull request by Areebah03**
*Fixed #629

### 🛠️ Fixes Issue (Number)

#629 

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

This is an amazing animation of a moving car with sound feature, build using HTML, CSS, Javascipt.

### 📷 Screenshots

ss1

### CODE REVIEW

**Comment by NOiR-07** [comment]
add your project in readme and cards.json file of website too

**Comment by Areebah03** [comment]
@NOiR-07  I have updated my project  in readme and cards.json file of website. Kindly view.

**Comment by NOiR-07** [comment]
remove the spaces to resolve the conflicts and also update your forked repo too

**Comment by Areebah03** [comment]
@NOiR-07  I have resolved the conflicts and updated the forked repo. Kindly view.

**Comment by Astrodevil** [comment]
@Areebah03 Sound is not working

**Comment by Areebah03** [comment]
@Astrodevil  I am making a new PR as there are a lot of issue in this PR  :(

**Pull request closed without merging**
