### PR TITLE
Added Multifunctioned Notes app

### PR DESCRIPTION
**Pull request by aaryahjolia**
### 👨‍💻 Changes proposed

Added Multifunctioned Notes app

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

GSSoC Contributor

### 📷 Screenshots

https://user-images.githubusercontent.com/82600388/167369948-540c4227-faf0-41c7-879a-6793eb2b2b7e.mp4

### CODE REVIEW

**Comment by Astrodevil** [comment]
Directory not followed

**Comment by aaryahjolia** [comment]
@Astrodevil Please review now

**Comment by NOiR-07** [comment]
update your forked repo once

**Comment by aaryahjolia** [comment]
Done @NOiR-07 Please review now

**Comment by NOiR-07** [comment]
also add your project in readme file

**Comment by Astrodevil** [comment]
@aaryahjolia make new PR properly

**Pull request closed without merging**
