### PR TITLE
Made the photo gallery as per issue #83

### PR DESCRIPTION
**Pull request by o0aman0o**

### CODE REVIEW

**Comment by Astrodevil** [comment]
Also add this project to landing page.

**Comment by NOiR-07** [comment]
@o0aman0o It's just displaying few pictures, is it really useful??
 Can you add some more features...

**Comment by o0aman0o** [comment]
umm...i can convert it to a podcast app....the images will be episode cover pics...the view be same but if you click on a particular pic...then it would start an episode..

**Comment by Astrodevil** [comment]
@o0aman0o are you making changes or its ready?

**Review by Astrodevil — COMMENTED** [review]
i am closing this for now.

**Pull request closed without merging**
