### PR TITLE
CV screener issue no 669

### PR DESCRIPTION
**Pull request by RiyaJain12**
this is a CV screener template .By use of this it became easy to see the application of candidates for job.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Screenshot (202)

### CODE REVIEW

**Comment by NOiR-07** [comment]
add this in the readme file too

**Comment by NOiR-07** [comment]
> add this in the readme file too

@RiyaJain12

**Comment by RiyaJain12** [comment]
> > add this in the readme file too
> 
> @RiyaJain12

Done!

**Comment by NOiR-07** [comment]
update the repo and change the project number in readme file

**Comment by RiyaJain12** [comment]
> update the repo and change the project number in readme file

Done!

**Pull request merged**
