### PR TITLE
added photo site project

### LINKED ISSUE #38: Want to add photo site web dev project

### PR DESCRIPTION
**Pull request by ManasviGoyal**
Fix #38

### CODE REVIEW

**Comment by NOiR-07** [comment]
Create a issue and mention the tag of issue here

**Comment by ManasviGoyal** [comment]
Hi. Is there any issue?

**Comment by Astrodevil** [comment]
Sorry for that, Your Css linkage is wrong. please make it correct.

**Comment by ManasviGoyal** [comment]
> Sorry for that, Your Css linkage is wrong. please make it correct.

Can pls specify

**Comment by Astrodevil** [comment]
> 
> 
> > Sorry for that, Your Css linkage is wrong. please make it correct.
> 
> Can you pls specify

you put this:     <link rel="stylesheet" href="style.css">  in html file.
                      but  you have to add "assets/css/photo_site.css" this in place of style.css

Please run the project you are contributing in your PC, If program is running fine in your pc, then make PR and provide Screenshot

that will be more helpful for you for removing errors

**Pull request merged**
