### PR TITLE
Add footer section to the website

### LINKED ISSUE #259: Add footer to the website
### **Feature Description**

I would like to add a footer section in the website to give it a complete look.

### **About feature**

- Will Contain social media icons
- Notice for all rights reserved
- Compliment the style of website

I am a GSSOC 2022 participant,
Kindly assign this issue to me

### PR DESCRIPTION
**Pull request by khushigupta123**
### 🛠️ Fixes Issue (Number)

 Closes #259 

### 👨‍💻 Changes proposed

I have added a footer section which contains following column:

**1.  About ZeroOctave Javascript project:** 

-  Add a bit of information about your website from Read Me file given on Git Hub.

**2.  Developers:** 

- Add developers name from main Git Hub Profile of ZeroOctave.
- Add arrow marks for list items.
- Add transition effects such as color change and slide right on hover. 

**3. Follow Us:**

- Add social media icons from font awesome.
- Add hover effect such as color change.
- Made social icons functional (only those whose links I could find on Git Hub).

**4. Copyright Notice:**

- Add copyright notice in this section.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

- I have made changes in index(HTML) and style(CSS) files.
- I have added comments in hard to understand areas.
- I have added link to google fonts and font awesome icons in head section.
- Footer section is completely responsive.

### 📷 Screenshots

Screenshot (15)

### CODE REVIEW

**Comment by Astrodevil** [comment]
Instead of adding developer names, Add contributor section take help from [here](https://levelup.gitconnected.com/displaying-contributors-image-on-readme-files-with-no-pain-f1cbaca963e8)

Only leave social media logos of existing link: Twitter,GitHub,Website,Mail. Remove others

**Comment by khushigupta123** [comment]
> Instead of adding developer names, Add contributor section take help from [here](https://levelup.gitconnected.com/displaying-contributors-image-on-readme-files-with-no-pain-f1cbaca963e8)
> 
> Only leave social media logos of existing link: Twitter,GitHub,Website,Mail. Remove others.
> 
> **Note:** Please update your fork.

Thank you for the review.

I have updated the social media icons.

Also, there is very less space available in the footer section for contributors. So, I would suggest that we should add some other attributes such as organizations ZeroOctave javascript project is a part of or tech stack used to develop this website or anything else that you may suggest.

Moreover, contributors will require a separate section before footer. I can raise a new issue for that and work on it should you wish.

Kindly inform me your opinion on this and I will make the suitable changes according to your instructions as soon as possible. 
Thank you

**Comment by Astrodevil** [comment]
Ok You can add changes you just mentioned & work on contributor section later.

**Comment by khushigupta123** [comment]
> Ok You can add changes you just mentioned & work on contributor section later.

okay sir

**Comment by khushigupta123** [comment]
> Ok You can add changes you just mentioned & work on contributor section later.

I have updated the collaborations section with the links of open source organizations ZeroOctave-Javascript-Projects is a part of.


Screenshot (16)

**Pull request merged**
