### PR TITLE
Added Random Anime Pics Generator project to the list...

### PR DESCRIPTION
**Pull request by AmolShelke2**
Hey, Project admin I've completed the issue that you assigned to me I've worked on it and completed the project and I'm creating the pull request to add on my Random Anime pic generator project to ZeroOctave-JavaScript-Projects Repository I hope that you go through my Pull Request and merged it..

and I'm attaching the Demo also please give it a look...

https://user-images.githubusercontent.com/95171638/156342107-e867d70d-61be-4238-bbdd-34b70803ab8c.mp4

### CODE REVIEW

**Comment by NOiR-07** [comment]
delete the json and icc.png file

**Comment by AmolShelke2** [comment]
> delete the json and icc.png file

Deleted the files please check..

**Comment by NOiR-07** [comment]
Also, add the project in the index file of the website, hence your project  would be visible on website

**Comment by AmolShelke2** [comment]
> Also, add the project in the index file of the website, hence your project would be visible on website

added anime app to the projects index.html please check it..

**Comment by NOiR-07** [comment]
@Astrodevil Please check their is some conflicts

**Comment by NOiR-07** [comment]
You have made a new index file i think, please don't do that
Just raise a new pr and don't change the index file, we'll do that later

**Pull request closed without merging**
