### PR TITLE
Parallex Design Effect Added

### PR DESCRIPTION
**Pull request by rajprem4214**
### 👨‍💻 Changes proposed
Made a new site that showcases the parallex design effect.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Parallex

### CODE REVIEW

**Comment by rajprem4214** [comment]
Resolved Conflicts. Please Review PR.

**Comment by rajprem4214** [comment]
@NOiR-07

**Comment by NOiR-07** [comment]
You've made so much changes in index file, you just had to add one card class for your project.

**Comment by rajprem4214** [comment]
Otherwise I may Create a new PR. If you insist

**Comment by NOiR-07** [comment]
yes make a new pr that will be better
closing this now

**Pull request closed without merging**
