### PR TITLE
Add a Tearable Cloth Project

### PR DESCRIPTION
**Pull request by mahiiverse1**
### 👨‍💻 Changes proposed

Added an interactive tearable cloth project. Drag the mouse over the cloth and tear it. Reset and change colours and patterns.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

Please let me know if I should update the project name in the README.md as well? I'll do the needful if necessary.

### 📷 Screenshots

[Deployed website](https://tearable-cloth-mahiiverse1.netlify.app/)

tearable-cloth

### CODE REVIEW

**Comment by Astrodevil** [comment]
Fix this error and your project on README
Screenshot 2022-05-29 235056

**Comment by mahiiverse1** [comment]
@Astrodevil just fixed the error please check once again!

**Comment by mahiiverse1** [comment]
@Astrodevil  not able to fetch upstream and update repo the repository it asks me to open a pull request for some reason. due to this im having issues updating readme

**Review by Astrodevil — COMMENTED** [review]
Don't remove dots, css and js not rendering.

**Comment by Astrodevil** [comment]
> @Astrodevil not able to fetch upstream and update repo the repository it asks me to open a pull request for some reason. due to this im having issues updating readme

Don't bother about README, I will do it

**Comment by mahiiverse1** [comment]
yes i noticed that and tried it on my own system and realized that for some
reason the extra dots were causing an error, once i removed them it started
working on my local system again...but I will look into it again if its not
working

**Pull request merged**
