### PR TITLE
modified tip calculator with tailwind css

### PR DESCRIPTION
**Pull request by Rancho2002**
### 👨‍💻 Changes proposed

modified tip calculator with tailwind CSS

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
Screenshot (119)

### CODE REVIEW

**Review by myhacktech — APPROVED** [review]

**Comment by myhacktech** [comment]
@Astrodevil

**Comment by myhacktech** [comment]
if there's a change in webpage.then attach that

**Comment by Rancho2002** [comment]
when someone opens the tip calculator via website, it looks like this
image

because in source code the CSS file is not properly addressed
image

Thats why I changed the path to 
image

**Comment by myhacktech** [comment]
is it working fine ...right?

**Comment by Rancho2002** [comment]
yes

**Review by myhacktech — APPROVED** [review]

**Comment by myhacktech** [comment]
LGTM @Astrodevil  please merge it

**Review by Astrodevil — APPROVED** [review]

**Pull request merged**
