### PR TITLE
Added Reflex Training Game

### LINKED ISSUE #540: Adding a Reflex Training web-app
**Is your feature request related to a problem? Please describe.**
- I want to add a reflex training game with minimal design to the repo. I believe that this will help beginners to learn about DOM navigation in JS and UI/UX with CSS.

**Additional context**

- I plan to complete this project in 4 days.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [ ] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

### PR DESCRIPTION
**Pull request by MonarchGitHub**
### 👨‍💻 Changes proposed

I have added a reflex training game to the repository, I will attach some screenshots of the game below.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
Kindly add level and Gssoc22 labels to the PR

### 📷 Screenshots
image
image

closes #540

### CODE REVIEW

**Comment by NOiR-07** [comment]
add your project in cards.json file of website

**Comment by MonarchGitHub** [comment]
@NOiR-07 I have updated the JSON file. Kindly review the changes.

**Comment by Astrodevil** [comment]
Please update json in alphabetical order, also update README with project details

**Comment by Astrodevil** [comment]
Last few days remaining, Complete your work till 31st.

**Comment by MonarchGitHub** [comment]
@Astrodevil I have updated the cards.json file in alphabetical order, kindly review.

**Comment by Astrodevil** [comment]
> @Astrodevil I have updated the cards.json file in alphabetical order, kindly review.

What about README? Please update your fork and add your project there.

**Comment by MonarchGitHub** [comment]
I have updated the README file. It slipped my mind previously.

**Pull request merged**
