### PR TITLE
Multiplication-table-generator,resolving issue #653

### PR DESCRIPTION
**Pull request by RiyaJain12**
calculate the multiplication table of any number depending upon the range given by the user.It will also pointer the cursor when mouse keepon the get button and will also change the color of the button to specify that the pointer is on the button.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Screenshot (138)

### CODE REVIEW

**Comment by NOiR-07** [comment]
update your forked repo once to resolve the conflict

**Comment by RiyaJain12** [comment]
@NOiR-07 
Done,kindly review it!

**Comment by Astrodevil** [comment]
> @NOiR-07 Done,kindly review it!

it's not generating table, make correction.

**Comment by Astrodevil** [comment]
@RiyaJain12 check properly. You haven't changed single line of code. Table is not generating

**Comment by Astrodevil** [comment]
@RiyaJain12 You still have time till evening. After that I will be closing this PR.

**Comment by RiyaJain12** [comment]
> @RiyaJain12 You still have time till evening. After that I will be closing this PR.

I open another pr for this ,because there is some issue from this.
plzz review it!!

**Pull request closed without merging**
