### PR TITLE
Added dynamic form

### PR DESCRIPTION
**Pull request by Whizz76**
Hi, I am a GSSOC'22 contributor and I added the react-dynamic-form.
issue number #493
form1
form2

### CODE REVIEW

**Comment by NOiR-07** [comment]
mention ur issue number and ss of project

**Comment by Whizz76** [comment]
Added joke api
issue number #514

**Comment by Whizz76** [comment]
Ok. I will make different pr for different issues

**Comment by Whizz76** [comment]
Have created different prs for each issue. Should I close this one?

**Pull request closed without merging**
