### PR TITLE
Adding the food theme flipping/memory game

### PR DESCRIPTION
**Pull request by soumali28**
### 👨‍💻 Changes proposed

Added the memory flipping game.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Memory Game - Google Chrome 11-04-2022 10_29_17

https://user-images.githubusercontent.com/66300439/162668429-dcc103eb-ec45-4ab6-b4a6-72098bbd051d.mp4

### CODE REVIEW

**Comment by soumali28** [comment]
ok

**Comment by soumali28** [comment]
I have changed all the files kindly review it.

**Comment by NOiR-07** [comment]
try to update your forked repo to remove the conflict

**Comment by soumali28** [comment]
Please check and merge it.

**Comment by NOiR-07** [comment]
there is still issue, i would suggest you to make a new pr for the same issue

**Comment by soumali28** [comment]
Ok

**Comment by soumali28** [comment]
I have created a new pr #509  kindly check it

**Pull request closed without merging**
