### PR TITLE
Added Arithmetic Calculator Project

### PR DESCRIPTION
**Pull request by TusharKesarwani**
### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
Kindly add level and Gssoc22 labels to the PR

### 📷 Screenshots
Calculator

### CODE REVIEW

**Comment by TusharKesarwani** [comment]
Kindly review my PR and add gssoc22 and level tag to the PR.

**Comment by TusharKesarwani** [comment]
Kindly review my PR and add gssoc22 and level tag to the PR.

**Comment by TusharKesarwani** [comment]
Kindly review my PR and add GSSoC'22 and level tag to the PR.

**Comment by NOiR-07** [comment]
mention issue number

**Comment by TusharKesarwani** [comment]
I have not created an issue. I'm adding a template so I directly made a PR without creating an issue.

**Comment by Astrodevil** [comment]
There are multiple calculator projects in this repository, Please check projects before making PR.

**Comment by TusharKesarwani** [comment]
In my project, the Calculator is somewhat different from others as in my calculator "Memory Functionality" is also added. So, I thought of contributing this project to this repository.

**Comment by TusharKesarwani** [comment]
No Problem with your comment @Astrodevil sir.

**Pull request closed without merging**
