### PR TITLE
Added udemy clone

### PR DESCRIPTION
**Pull request by Sulagna-Dutta-Roy**
Fixes: #456 

### 👨‍💻 Changes proposed

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Udemy-clone

### CODE REVIEW

**Comment by sreelakshmig009** [comment]
image
@Sulagna-Dutta-Roy The login and signup buttons positions needs to be changed

**Comment by Sulagna-Dutta-Roy** [comment]
Why ?? I've checked the real udemy page where the buttons looks like this ?.

**Comment by Astrodevil** [comment]
@Sulagna-Dutta-Roy Are you changing something? with apple need space, Log In has small i

**Comment by Sulagna-Dutta-Roy** [comment]
Okay I will add the changes.

**Comment by Sulagna-Dutta-Roy** [comment]
> image
> @Sulagna-Dutta-Roy The login and signup buttons positions needs to be changed

In my device it's working fine.

**Comment by Astrodevil** [comment]
> > image
> > @Sulagna-Dutta-Roy The login and signup buttons positions needs to be changed
> 
> In my device it's working fine.

see carefully (continue with apple)

**Pull request closed without merging**
