### PR TITLE
Country Capital Webpage

### PR DESCRIPTION
**Pull request by Sukriti-m**
### 👨‍💻 Changes proposed

I have added the Country Capital Webpage

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

I am a GSSoC'22 contributor. Please review this PR. @Astrodevil 

### Screenshots

cc

cc1

### Videos

https://user-images.githubusercontent.com/93239528/165343232-0341c3ca-9c90-40ae-ab35-51099701fce0.mp4

### CODE REVIEW

**Comment by Astrodevil** [comment]
Please add files in respective folders. Don't create one.

**Comment by Sukriti-m** [comment]
> Please add files in respective folders. Don't create one.

I have made the required changes. Please review.

**Comment by Astrodevil** [comment]
Also add your project in cards.json in alphabetical order and README after updating fork.

**Comment by Sukriti-m** [comment]
> Also add your project in cards.json in alphabetical order and README after updating fork.

I have made the required changes. Please review.

**Pull request merged**
