### PR TITLE
Responsive Range-Slider Added!

### PR DESCRIPTION
**Pull request by KiranAminPanjwani**
### 👨‍💻 Changes proposed

- I have added a range slider project (HTML, CSS, javascript).

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

- Fully responsive.
- Good practice for JS learners.

### 📷 Screenshots

image

image

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
@Astrodevil Kindly review and merge it. Thank you.

**Comment by KiranAminPanjwani** [comment]
> Thank you @KiranAminPanjwani for taking out your valuable time in order to contribute to our project. Looking forward for more such amazing contributions :)

Shall I add my project to your website as well?✨

**Comment by Astrodevil** [comment]
Check it first.

**Comment by KiranAminPanjwani** [comment]
> Check it first.

Okay

**Pull request merged**
