### PR TITLE
Added dynamic picture frame

### PR DESCRIPTION
**Pull request by Whizz76**
### 🛠️ Fixes Issue (618)

fixed issue #618 

### 👨‍💻 Changes proposed

Added index.html file
Added style.css file
Added script.js file

### ✅ Check List (Check all the applicable boxes) 

- ✅My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- ✅This PR does not contain plagiarized content.
- ✅ My Addition/Changes works properly and matches the overall repo pattern.
- ✅ The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

Added the dynamic Picture Frame

### 📷 Screenshots
pic

### CODE REVIEW

**Comment by Astrodevil** [comment]
You are not following proper directory order of this repo, Please put files in respective folders and update cards.json & README.

**Comment by Whizz76** [comment]
Ok. Will do so quickly

**Comment by Whizz76** [comment]
Added pf folder in public folder and updated cards.json and readme

**Comment by Whizz76** [comment]
Had made changes and subsequently created a new pr. Should I close this one?

**Pull request closed without merging**
