### PR TITLE
Student Enrollment form project added

### PR DESCRIPTION
**Pull request by muskan467**
### 👨‍💻 Changes proposed

This project takes the required inputs from the user and displays the details of enrolled students.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

student-enrollment-form

### CODE REVIEW

**Comment by myhacktech** [comment]
attach ss with explaination @muskan467

**Comment by myhacktech** [comment]
mention issue with # in description

**Comment by muskan467** [comment]
@myhacktech I have edited it

**Review by myhacktech — DISMISSED** [review]

**Comment by muskan467** [comment]
@Astrodevil Please review it

**Pull request closed without merging**
