### PR TITLE
Markdown Rendering Complete [SSOC]

### PR DESCRIPTION
**Pull request by Krishna-bansall**
### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
I've applied the renderer so it will show documentation for all projects before opening them
it would be a good idea to announce on discord channel maybe asking volunteers to document the repository

### CODE REVIEW

**Comment by myhacktech** [comment]
attach ss?

**Comment by Krishna-bansall** [comment]
ah sorry my bad here
[image: image.png]
[image: image.png]

**Comment by Astrodevil** [comment]
Sorry for late reply, but I think readme is not rendering on website and your SS is not visible,, use github to share screenshot.

**Comment by Krishna-bansall** [comment]
Sorry for the late reply, 
I am not sure what's going on here, this is working just fine on my pc 

Peek 2022-10-03 16-51

**Comment by Anmol-Baranwal** [comment]
@Krishna-bansall 

I don't really understand, the changes you have done is for which purpose? Is it resolving the live website issues?

Please, write a brief info about the code changes

**Comment by Astrodevil** [comment]
I am getting this by my side. Please solve conflicts and tell me the usecase of .history folder

image

**Pull request closed without merging**
