### PR TITLE
Speech to text Converter program added

### PR DESCRIPTION
**Pull request by Aayush987**
-This pr is with reference with the issue: #180 

# Description
  A simple speech-to-text converter program made from HTML, Javascript, CSS.
  This Pr is under the contributions in GSSOC'22.
# Sample Video 

https://user-images.githubusercontent.com/92387745/157084213-e4d1bfa2-2fea-4986-b9de-113e72a22142.mp4

### CODE REVIEW

**Comment by NOiR-07** [comment]
Make separate files for css and js 
Internal/Inline CSS are not preferred in this repo

**Comment by Aayush987** [comment]
> Make separate files for css and js Internal/Inline CSS are not preferred in this repo

OK.

**Comment by Aayush987** [comment]
> Make separate files for css and js Internal/Inline CSS are not preferred in this repo

Done

**Comment by NOiR-07** [comment]
Bro don't make separate folders
keep the html file in public/
css in assets/css/
js in assets/js/

**Comment by Aayush987** [comment]
> Bro don't make separate folders
> keep the html file in public/
> css in assets/css/
> js in assets/js/

Oh I am so sorry I did not understood it previously

**Comment by NOiR-07** [comment]
> > Bro don't make separate folders
> > keep the html file in public/
> > css in assets/css/
> > js in assets/js/
> 
> Oh I am so sorry I did not understood it previously

no issues

**Comment by Astrodevil** [comment]
All good, just add your project in index.html (landing page) file also by commenting out. Please update your fork before this.

**Comment by Aayush987** [comment]
> All good, just add your project in index.html (landing page) file also by commenting out. Please update your fork before this.

Can you tell me command line git command to update the fork because I was doing it in other repo and it got all the updates as commit.

**Comment by Astrodevil** [comment]
@Aayush987 check this out https://medium.com/@sahoosunilkumar/how-to-update-a-fork-in-git-95a7daadc14e

**Comment by Aayush987** [comment]
> @Aayush987 check this out https://medium.com/@sahoosunilkumar/how-to-update-a-fork-in-git-95a7daadc14e

Thank you

**Comment by Aayush987** [comment]
> All good, just add your project in index.html (landing page) file also by commenting out. Please update your fork before this.

Done.

**Comment by Aayush987** [comment]
> can you share a mini video to show how it works

Sure.

**Pull request merged**
