### PR TITLE
Social tray, new feature added

### PR DESCRIPTION
**Pull request by VasuDevrani**
### 👨‍💻 Changes proposed

Added a new feature. It is present in a folder named 'SocialTray' with html and css files

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

Please merge the request and add it to the website
[DEMO](https://rococo-praline-28f4e4.netlify.app/)

### CODE REVIEW

**Comment by Astrodevil** [comment]
You are not following directory order for this repository, Please make corrections

**Comment by Astrodevil** [comment]
See carefully, In this repository public contains only html files and it contains a folder only if there are multiple html files for the same project.

**Comment by VasuDevrani** [comment]
Got it @Astrodevil 
Then what should I do? Should I create ***html files*** only or add the folder ***outside public***.
Thanks

**Comment by Astrodevil** [comment]
Delete the folder just drop html file inside public and css file in assets/css folder and change your linkage accordingly.

**Comment by VasuDevrani** [comment]
Okay got it now....Thank you
I'll do it, sorry for the mistake....

**Comment by VasuDevrani** [comment]
Hey @Astrodevil, done with the task
***Public/SocialTray/socialTray.html → Public/socialTray.html***

***Public/SocialTray/socialTray.css → assets/css/socialTray.css***

**Comment by VasuDevrani** [comment]
Hey @Astrodevil, done with the task
Rearranged files and linked as well....

**Comment by Astrodevil** [comment]
Is this for Ssoc?

**Comment by VasuDevrani** [comment]
Nope!! I'm just contributing for the good
Would you merge it now? I mean... Everything alright?

**Comment by Astrodevil** [comment]
Yes, working fine

**Comment by Astrodevil** [comment]
Please also add this project in cards.json and README in new PR.

**Comment by VasuDevrani** [comment]
Thanks A Lot...

**Pull request merged**
