### PR TITLE
Whack a mole.

### PR DESCRIPTION
**Pull request by Avik-creator**
Worked on Issue Number : #467 
Made it using JS.
I can assure that it was not plagiarised.
It was a fun project to made.

### CODE REVIEW

**Comment by Avik-creator** [comment]
@NOiR-07 please check and review it.

**Comment by NOiR-07** [comment]
add your project in the index and cardsdata file

**Comment by Avik-creator** [comment]
How to add in them?

**Comment by Avik-creator** [comment]
@NOiR-07

**Comment by NOiR-07** [comment]
> How to add in them?

you can see how others have done, just need to change the name to your project name

**Comment by Avik-creator** [comment]
Ok just giving all the index content of my file to the main index file of your project?

**Comment by NOiR-07** [comment]
there is some changes as We've changes the files for the website, so i suggest you to update your forked repo and add your project in cards.json and readme instead of index and cardsdata file

**Pull request closed without merging**
