### PR TITLE
Added buttons for  x^2,  x^y,  sqrt(x),  log(x) ,  兀,  e in Calculator

### PR DESCRIPTION
**Pull request by aditya-464**
### 👨‍💻 Changes proposed

Added a new column of buttons for  兀,  e,   x^2,  x^y,  sqrt(x)  and  log(x)  operations.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Screenshot (695)

### CODE REVIEW

**Comment by aditya-464** [comment]
#### @Astrodevil  @myhacktech  Please anyone of you review my pull request

**Review by myhacktech — APPROVED** [review]
Lgtm @Astrodevil

**Comment by aditya-464** [comment]
> Lgtm @Astrodevil

@myhacktech Please add the "hacktoberfest" and "hacktoberfest-accepted" labels

**Comment by myhacktech** [comment]
> > Lgtm @Astrodevil
> 
> @myhacktech Please add the "hacktoberfest" and "hacktoberfest-accepted" labels

I am mentor for ssoc,contest ends today

**Review by Astrodevil — APPROVED** [review]

**Pull request merged**
