### PR TITLE
Added a new Shell Game

### PR DESCRIPTION
**Pull request by leader282**
### 👨‍💻 Changes proposed
Adding a whole new game so no such changes in any existing project.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
The game works perfectly fine and many interesting features like dynamic trace paths and game level difficulty is added and so it took a long time to open the PR.

### 📷 Screenshots
Shell_game1
Shell_game2
Shell_game3

### CODE REVIEW

**Comment by NOiR-07** [comment]
Add your project on the website too

**Comment by leader282** [comment]
> Add your project on the website too

Can you please guide me on how to proceed with that?

**Comment by Astrodevil** [comment]
> > Add your project on the website too
> 
> Can you please guide me on how to proceed with that? I tried but could not proceed.

You have to update your fork and open index.html & go through the file, there is a comment for each project you will have to put similar lines of code with comments with your project and relevant details.

**Comment by leader282** [comment]
> > > Add your project on the website too
> > 
> > 
> > Can you please guide me on how to proceed with that? I tried but could not proceed.
> 
> You have to update your fork and open index.html & go through the file, there is a comment for each project you will have to put similar lines of code with comments with your project and relevant details.
> 
> Also delete DS store file from your commit.

Done all the required changes. Please review the PR once.

**Pull request merged**
