### PR TITLE
Added Responsive Landing Page with Dark and light toggle

### PR DESCRIPTION
**Pull request by AmolShelke2**
### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

Hey, project admin as you assign me this issue to work on I have completed the project and created the pr regarding that I hope that you will go through my pull request and merge it.

### 📷 Screenshots

responsiveWeb png

### CODE REVIEW

**Comment by NOiR-07** [comment]
delete the json file and add your project in the index and cardsdata file too

**Comment by AmolShelke2** [comment]
Hey Abhishek I have changed the code and added my project to project's
index.html file so please go through it and review it thanks 🙂

**Comment by AmolShelke2** [comment]
@NOiR-07 Please review the PR I have done the changes

**Comment by NOiR-07** [comment]
you haven't added in the index file of website
for ref: check others code how they did

**Review by AmolShelke2 — COMMENTED** [review]
I have added my project to index.html please check it properly

**Comment by AmolShelke2** [comment]
> you haven't added in the index file of website for ref: check others code how they did
@NOiR-07 look at this
index html - ZeroOctave-Javascript-Projects - Visual Studio Code 13-04-2022 4 26 25 PM

**Comment by AmolShelke2** [comment]
> How do I update the forked repo
@NOiR-07  please add a level label on pr

**Comment by AmolShelke2** [comment]
Hey, @NOiR-07 Please add a level label on my pull request. I have fixed the conflicts

**Pull request merged**
