### PR TITLE
Added Linkedin UI to the ZeroOctave-JavaScript-Projects.

### LINKED ISSUE #525: I will add a Linkedin UI clone to the current repository.
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like** 
 Hey project admin I'm a GSSOC participant and I want to add a LinkedIn homepage clone created with HTML CSS and javaScript to the current repository please assign me this issue to work on.

**Additional context**
Screenshot-1

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through the project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

### PR DESCRIPTION
**Pull request by AmolShelke2**
### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

I hope that you all are doing great kindly review this pull request and go through my pull request.

### CODE REVIEW

**Comment by AmolShelke2** [comment]
@Astrodevil kindly review this PR

**Comment by AmolShelke2** [comment]
@Astrodevil if you are not merging this pull request kindly close it why you are not responding to this pull request..

**Comment by Astrodevil** [comment]
You need to update cards.json and README with project details after updating fork. Don't make changes in index.html

**Comment by AmolShelke2** [comment]
@Astrodevil kindly close this Pull request I will create the new pr with all needed files because. every file is being collided some of the files are not showing in this.

**Pull request closed without merging**
