### PR TITLE
Added Picture-frame

### PR DESCRIPTION
**Pull request by Whizz76**
### 🛠️ Fixes Issue 618
fixed issue #618 

### ✅ Check List (Check all the applicable boxes) 

- [ ✅ ] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [ ✅ ] This PR does not contain plagiarized content.
- [ ✅ ] My Addition/Changes works properly and matches the overall repo pattern.
- [✅  ] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

pp

### CODE REVIEW

**Review by Astrodevil — CHANGES_REQUESTED** [review]
Your json addition is wrong, please also add image.

**Comment by Astrodevil** [comment]
@Whizz76  You still have time till evening. After that I will be closing this PR.

**Comment by Whizz76** [comment]
What image are you asking to add? in my picture frame, I have used an image link and not an image from picture-frame folder.

**Comment by Whizz76** [comment]
Ok. I am adding now.

**Review by Astrodevil — APPROVED** [review]

**Pull request merged**
