### PR TITLE
Added tinder clone

### LINKED ISSUE #483: Adding a Tinder Clone Webapp
Building a Tinder Clone web application

### PR DESCRIPTION
**Pull request by TG922**
### 🛠️ Fixes Issue (Number)

Closes #483

### 👨‍💻 Changes proposed

- Added tinder clone web application.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Image99

### CODE REVIEW

**Comment by NOiR-07** [comment]
First, wait for the issue to get assigned before making a PR and add your project in index file of website too

**Comment by TG922** [comment]
> First, wait for the issue to get assigned before making a PR and add your project in index file of website too

Sure @NOiR-07 It was my first time, Creating PR before being assigned.

**Comment by NOiR-07** [comment]
make a folder in assets/css to keep both CSS files together
add your project in index and cardsdata file

**Comment by TG922** [comment]
Ok will do today ASAP

**Comment by TG922** [comment]
Sorry for the delay I was busy in SIH 22 and will complete it ASAP.

**Pull request closed without merging**
