### PR TITLE
Update README.md for Switching Testimonial Box 

### PR DESCRIPTION
**Pull request by VaishnaviMandloi**
`<!--` Remove the sections which are not applicable -->

### 👨‍💻 Changes proposed
Updated readme as told in #747  

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by VaishnaviMandloi** [comment]
@NOiR-07 @Astrodevil  please check now

**Comment by Astrodevil** [comment]
> @NOiR-07 @Astrodevil please check now

https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/pull/747#issuecomment-1140273125

**Comment by VaishnaviMandloi** [comment]
@Astrodevil what I have to do now in this pr ?

**Comment by Astrodevil** [comment]
> @Astrodevil what I have to do now in this pr ?

Your last PR was reverted due to some errors. please push changes again.

**Comment by NOiR-07** [comment]
@VaishnaviMandloi make a new pr for the same earlier you made, just change the project number in readme
make sure to update your forked repo first

**Pull request closed without merging**
