### PR TITLE
Add Check my IP

### PR DESCRIPTION
**Pull request by kislow**
### 👨‍💻 Changes proposed

Project Check my IP Added 

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

This is a suitable project for web dev beginners. There are a few features that newbies could add, such as:

- light/dark mode
- make it more responsive
- retrieve and display local IP address etc.

### 📷 Screenshots

Show my ip

### CODE REVIEW

**Comment by NOiR-07** [comment]
just add your files and change the filename, do not make a separate folder for a single file

**Comment by NOiR-07** [comment]
just add your files and change the filename, do not make a separate folder for a single file

**Comment by kislow** [comment]
> just add your files and change the filename, do not make a separate folder for a single file

Fixed!

**Comment by Astrodevil** [comment]
add your project in cards.json alphabatically

**Comment by kislow** [comment]
> add your project in cards.json alphabatically

Done!

**Comment by Astrodevil** [comment]
@NOiR-07 Please check the working and merge it.

**Pull request merged**
