### PR TITLE
Add a book shopping website

### LINKED ISSUE #432: Add a book shopping website
**Is your feature request related to a problem? Please describe.**
I want to add a book shopping website to this project.

**Describe the solution you'd like**
I wanted to contribute by adding a book shopping website to this project. The website is made of purely HTML, CSS and JavaScript. Users can add books to the cart and make a purchase. (on purchasing it just shows "successful purchase pop up".

**Additional context**
booknbuyss

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through the project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

### PR DESCRIPTION
**Pull request by mahiiverse1**
### 🛠️ Fixes Issue #432 

Closes #432 

### 👨‍💻 Changes proposed

1. Added a new project of a book shopping website
2. The website is multipage and built using HTML, CSS, Javascript.
3. Users can add books to cart in cart section.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

Link of deployed website - https://booknbuy.000webhostapp.com/

### 📷 Screenshots

BOOKBUY
bookbuy2
bookbuy3
bookbuy4
bookbuy5

### CODE REVIEW

**Comment by NOiR-07** [comment]
don't make a separate folder, instead, follow the repo format to place your files
also, add your project in the index and cardsdata file too

**Comment by mahiiverse1** [comment]
@NOiR-07 Noted, just to ask, i have two html & js files, so do i add both html files in public as a file?

And sure I'll add the projects in index as well as cardsdata asap

**Comment by mahiiverse1** [comment]
@NOiR-07 just updated everything please do check!

**Comment by NOiR-07** [comment]
correct the location of css given in book.html file

**Comment by mahiiverse1** [comment]
@NOiR-07 just changed locations of css and js, please do check once!

**Pull request merged**
