### PR TITLE
Grocery manager added

### PR DESCRIPTION
**Pull request by piyusha2001**
### 👨‍💻 Changes proposed

Added grocery manager project

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
Video

https://user-images.githubusercontent.com/81703477/170814868-e9fdc9e1-e30c-418e-9cf8-f68460513ae7.mp4

### CODE REVIEW

**Comment by piyusha2001** [comment]
@Astrodevil  please review my PR

**Comment by Astrodevil** [comment]
Cards.json not updated alphabetically and README updation is wrong. @piyusha2001 Please make changes in new PR.

**Comment by piyusha2001** [comment]
> Cards.json not updated alphabetically and README updation is wrong. @piyusha2001 Please make changes in new PR.
Oh sorry! I didnt notice that . But the issue is closed now..can u open it again? Or will I have to do that?

**Comment by piyusha2001** [comment]
@Astrodevil Hey readme is updated right

**Comment by Astrodevil** [comment]
>  @Astrodevil Hey readme is updated right
> 
> 

Is it correct?

**Comment by piyusha2001** [comment]
> > @Astrodevil Hey readme is updated right
> 
> Is it correct?

Sorry it isnt . My bad . What should I do? Open a new issue?

**Comment by Astrodevil** [comment]
Just made correction in cards.json and readme in new PR. No need for Issue.

**Comment by piyusha2001** [comment]
> Just made correction in cards.json and readme in new PR. No need for Issue.

Okay.

**Comment by piyusha2001** [comment]
@Astrodevil  I have made a PR for this

> Just made correction in cards.json and readme in new PR. No need for Issue.

I have made PR for this . Also can u increase level tag? I mean CRUD operations are something very important and i have implemented it in pure js . Please give it a thought.

**Pull request merged**
