### PR TITLE
Star Catching Game Added

### PR DESCRIPTION
**Pull request by shreya024**
I have added the Star Catching Game maintaing folders as html,images and js.

### CODE REVIEW

**Comment by NOiR-07** [comment]
Mention the issue tag

**Comment by shreya024** [comment]
Star-Catching Game #49

**Comment by NOiR-07** [comment]
Provide the ss or gif of your project

**Comment by shreya024** [comment]
image

**Comment by shreya024** [comment]
@NOiR-07 Thank you so much, this PR just completed the 14 days review period and got accepted into Hactoberfest :)

**Comment by NOiR-07** [comment]
> @NOiR-07 Thank you so much, this PR just completed the 14 days review period and got accepted into Hactoberfest :)

Congratulations 🎉🎉 Hope to see you contributing here again in upcoming programs.....

**Pull request merged**
