### PR TITLE
Added a code to accordion

### PR DESCRIPTION
**Pull request by Palaksharma23**
https://user-images.githubusercontent.com/87171452/144737171-c0929e8a-f709-4919-a8c1-090e6561a974.mp4

### CODE REVIEW

**Comment by NOiR-07** [comment]
@Palaksharma23 as I can see in the video there is only some random words are written, it would be better if u write some quotes or something meaningful.

**Comment by Palaksharma23** [comment]
Okay sure sir @NOiR-07

**Comment by Palaksharma23** [comment]
Done sir :)

**Comment by NOiR-07** [comment]
@Palaksharma23 great 👍
From next time i would suggest you to use external CSS instead of inline or internal, as this is followed by most of the projects in this repository

**Pull request merged**
