### PR TITLE
Added my developer portfolio website

### LINKED ISSUE #330: Developer portfolio website
This developer portfolio website is made using HTML , CSS and javascript . It is entirely responsive as well as has minimal UI.<br><br>
Landing Page :<br>
Screenshot (628)<br><br>
Screenshot (629)

@JayantGoel001 kindly assign me the issue to start working on the project.

### PR DESCRIPTION
**Pull request by MannyP31**
### 🛠️ Fixes Issue (Number)

 Closes #330 

### 👨‍💻 Changes proposed

Added a new project . Link to view website : https://mannyp31.github.io/Dev-folio-2/

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots<br>
multi-portfolio<br>
Screenshot (635)<br>
Screenshot (636)<br>

Screenshot (638)<br>
Screenshot (637)<br>

Screenshot (639)<br>

### CODE REVIEW

**Comment by sreelakshmig009** [comment]
@MannyP31 The css is not linked properly. It doesnt get reflected

image

**Comment by MannyP31** [comment]
> @MannyP31 The css is not linked properly. It doesnt get reflected
> 
> image

@sreelakshmig009 I have made the necessary changes , kindly go through them and tell me whether it's working or not .

**Comment by MannyP31** [comment]
@Astrodevil What does this need review tag actually means ? Is my project alright or do I need to make more changes ?

**Comment by Astrodevil** [comment]
> @Astrodevil What does this need review tag actually means ? Is my project alright or do I need to make more changes ?

This Tag is for maintainers to remind before merging. You will be informed if any change needed.

**Comment by MannyP31** [comment]
> > @Astrodevil What does this need review tag actually means ? Is my project alright or do I need to make more changes ?
> 
> This Tag is for maintainers to remind before merging. You will be informed if any change needed.

Okay Thanks a lot !!

**Pull request merged**
