### PR TITLE
resume builder added

### PR DESCRIPTION
**Pull request by tarce09**
issue no #78 
Hello sir,
I added a html, css and js based resume builder where you can fill in your details in a professionally designed resume and download the resume in pdf format.
I would be very glad if you accept my pr
the file name is resume_builder in the assets folder

### CODE REVIEW

**Comment by NOiR-07** [comment]
@tarce09 Always first raise the issue and when it's assigned to you then raise the pr, do the same for this
 Also, try to put the ss/gif of your running project so that we can verify

**Comment by tarce09** [comment]
thank you for your guidance i have added the issue,
do i have to pull req again or will this pull request be good

**Comment by NOiR-07** [comment]
> thank you for your guidance i have added the issue, do i have to pull req again or will this pull request be good

Just mention the issue tag

**Comment by tarce09** [comment]
i have mentioned the issue tag by editing the initial comment of the pull request is it fine now

**Pull request merged**
