### PR TITLE
Added Random Quote Generator

### PR DESCRIPTION
**Pull request by Sulagna-Dutta-Roy**
### 🛠️ Fixes Issue (Number)

#523 

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Random_Quote

### CODE REVIEW

**Comment by Astrodevil** [comment]
I instructed you to merge all commits into one, but you closed the PR twice. It's ok
But you haven't updated README properly. Please do it after updating your fork.

**Comment by Sulagna-Dutta-Roy** [comment]
Everytime I update the readme , there is merge conflicts even I've solve it.

**Comment by Astrodevil** [comment]
> Everytime I update the readme , there is merge conflicts even I've solve it.

You have to update README after updating fork and if there is conflicts you can resolve it. Conflicts are just some repetitive lines of code. Try to solve that instead of closing PRs. [watch this](https://www.youtube.com/watch?v=JtIX3HJKwfo)

**Comment by Sulagna-Dutta-Roy** [comment]
I've done the changes please check.

**Pull request merged**
