### PR TITLE
Added Brick Breakout Game in HTML CSS and JS

### PR DESCRIPTION
**Pull request by pranjay-poddar**
### 👨‍💻 Changes proposed

Added Brick Breakout Game in HTML CSS and JS

### ✅ Check List (Check all the applicable boxes) 

- [X] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [X] This PR does not contain plagiarized content.
- [X] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
image

### CODE REVIEW

**Comment by pranjay-poddar** [comment]
@Astrodevil @sreelakshmig009 pls review my PR

**Comment by NOiR-07** [comment]
don't remove any line of code from readme, just add your line of code
resolve this conflict

**Comment by Astrodevil** [comment]
Your project is not added in README, please do that

**Comment by pranjay-poddar** [comment]
@Astrodevil corrected the Project and also resolved the conflicts please check.

**Comment by pranjay-poddar** [comment]
Final Render 
image

**Comment by Astrodevil** [comment]
I think you pushed files of another projectI think you pushed files of other project

**Comment by pranjay-poddar** [comment]
@Astrodevil done with the corrections, pls check.

**Comment by pranjay-poddar** [comment]
@Astrodevil please merge this PR I have been resolving the readme issue again n again due to other PR merges that take place in between. Hope u understand.

**Comment by Astrodevil** [comment]
> @Astrodevil please merge this PR I have been resolving the readme issue again n again due to other PR merges that take place in between. Hope u understand.

I will solve that readme conflict,no issue👍🏻. Just made sure you make the main changes properly.

**Comment by pranjay-poddar** [comment]
> > @Astrodevil please merge this PR I have been resolving the readme issue again n again due to other PR merges that take place in between. Hope u understand.
> 
> I will solve that readme conflict, no issue👍🏻. Just made sure you make the main changes properly.

Done with the change it is updated to be merged.

**Comment by Astrodevil** [comment]
Still same error, You didn,t fixed the error. instead you pushed a different project folder and deleted it.  You can also make new PR if you want to

**Pull request closed without merging**
