### PR TITLE
Added dad's Joke application 

### PR DESCRIPTION
**Pull request by pranjay-poddar**
### ✅ Check List (Check all the applicable boxes) 

- [X] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [X] This PR does not contain plagiarized content.
- [X] My Addition/Changes works properly and matches the overall repo pattern.
- [X] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Astrodevil** [comment]
Don't need commits related to #615. Solve conflicts

**Comment by pranjay-poddar** [comment]
@Astrodevil Conflicts Resolved

**Comment by pranjay-poddar** [comment]
> Don't need commits related to #615. Solve conflicts

Since I have also worked on adding other missing projects to readme I added to issue #615 with this one.

**Comment by Astrodevil** [comment]
> > Don't need commits related to #615. Solve conflicts
> 
> Since I have also worked on adding other missing projects to readme I added to issue #615 with this one.

It's already been merged .

**Comment by pranjay-poddar** [comment]
@Astrodevil I have removed commit related to #615

**Pull request merged**
