### PR TITLE
NGO website with Payment gateway Integrated

### PR DESCRIPTION
**Pull request by KshitizSharma11**
this simple website is built using HTML and CSS and is powered by Razorpay API and gateway

This is in reference to #50

### CODE REVIEW

**Comment by KshitizSharma11** [comment]
@NOiR-07 Is it fine now?

**Comment by NOiR-07** [comment]
<link rel="stylesheet" href="NGO.css">
Change the folder here by assets/css/foldername

**Comment by KshitizSharma11** [comment]
@NOiR-07  I have updated the HTML file

**Comment by KshitizSharma11** [comment]
Now it must work 🤞 @NOiR-07

**Pull request merged**
