### PR TITLE
Added "QR Code Generator" webpage 

### LINKED ISSUE #411: Add "QR Code Generator"
**Is your feature request related to a problem? Please describe.**
many times we need QR code to share link or text.

**Describe the solution you'd like**
I want to add a webpage which will generate QR code for text or link inserted by user.

**Additional context**
Some UI Screenshots are: 
Frame 1 (3)
Frame 2 (1)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

### PR DESCRIPTION
**Pull request by SachinMittal1766**
### 🛠️ Fixes Issue (Number)
Closes #411

### 👨‍💻 Changes proposed

1. added html, css, js, image for webpage
2. Added webpage link in index.html file

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by NOiR-07** [comment]
Also add your project data in cardsdata.js

**Comment by SachinMittal1766** [comment]
@NOiR-07 Done

**Comment by SachinMittal1766** [comment]
@NOiR-07 Pls merge my PR

**Comment by SachinMittal1766** [comment]
@NOiR-07 @Astrodevil Hey, I have created PR 9 days ago but it is not merged yet.

**Comment by NOiR-07** [comment]
> @NOiR-07 @Astrodevil Hey, I have created PR 9 days ago but it is not merged yet.

reviewing it, you've to give us sometime

**Pull request merged**
