### PR TITLE
grocery manager project added

### LINKED ISSUE #687: Grocery Items Manager
**Is your feature request related to a problem? Please describe.**
Many times we forget some or the other grocery item to bring . Hence to avoid that we can make use of grocery items manager.Please assign me this issue under GSSoC'22

**Describe the solution you'd like**
A grocery items manager would be a web application made using Javascript  in which user can add names of a grocery items which will be shown in the form of list , user will be able to delete a certain item and also edit a certain item .

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

### PR DESCRIPTION
**Pull request by piyusha2001**
### 🛠️ Fixes Issue (687)

Closes #687 

### 👨‍💻 Changes proposed

Added grocery manager project

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Screenshot 2022-05-25 014152

### CODE REVIEW

**Comment by NOiR-07** [comment]
you've deleted and pasted many lines in readme which is breaking the flow, just add your line of code

**Comment by piyusha2001** [comment]
> you've deleted and pasted many lines in readme which is breaking the flow, just add your line of code

I didnt delete anything..but i will look into it as there are some merge conflicts

**Comment by piyusha2001** [comment]
@NOiR-07  Hey i have resolved merge conflicts and added only my line of code in readme and cards.json .Please review this PR

**Comment by Astrodevil** [comment]
@piyusha2001 I request you to create a new PR with updated fork. You break the README and some json.

**Pull request closed without merging**
