### PR TITLE
Netflix Clone

### PR DESCRIPTION
**Pull request by dsasaank-369**
### 👨‍💻 Changes proposed
   Added a folder named Netflix Clone in the public folder.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
   Please install npm modules for the proper execution of the code.

### 📷 Screenshots
image

### CODE REVIEW

**Comment by NOiR-07** [comment]
don't make a separate folder, instead, follow the repo format to place your files
also, add your project in the index and cardsdata file too

**Comment by dsasaank-369** [comment]
There are many files so, can I know where should I add

**Comment by NOiR-07** [comment]
make a folder in public folder to place all HTML files there, and repeat the same for CSS and js(make a folder in assets/css for CSS files and assets/js for the same)

**Comment by dsasaank-369** [comment]
Please check, I have corrected the placement of all files.

**Comment by NOiR-07** [comment]
you've made the website using react, but this repo is for HTML,CSS,js projects
You can raise issue on other Projects based on react

**Pull request closed without merging**
