### PR TITLE
Added Birthday Greeting files.

### PR DESCRIPTION
**Pull request by Anchita15**
### 👨‍💻 Changes proposed

Added Birthday greeting files.
This is made using HTML, CSS, JavaScript and gives an good insight in the same. 

### ✅ Check List (Check all the applicable boxes) 

- [✅] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [✅]  This PR does not contain plagiarized content.
- [✅]  My Addition/Changes works properly and matches the overall repo pattern.
- [✅]  The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Screenshot 2022-03-01 144936
Screenshot 2022-03-01 144958

### CODE REVIEW

**Comment by NOiR-07** [comment]
try to improve your project it's very basic and simple

**Comment by NOiR-07** [comment]
@Anchita15 Any updates?

**Comment by Anchita15** [comment]
> @Anchita15 Any updates?

Yeah, I'm working on it.

**Comment by Astrodevil** [comment]
@Anchita15 You still have time till evening. After that I will be closing this PR.

**Pull request closed without merging**
