### PR TITLE
Updated the Readme

### PR DESCRIPTION
**Pull request by ayush-sleeping**
### 👨‍💻 Changes proposed

For Output Visit here  : https://github.com/ayush-sleeping/ZeroOctave-Javascript-Projects/blob/main/README.md

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

Hey maintainer , Checkout this PR and if all things are good to go , Kindly merge it ..........

### 📷 Screenshots

For Final Output Visit here  : https://github.com/ayush-sleeping/ZeroOctave-Javascript-Projects/blob/main/README.md

### CODE REVIEW

**Comment by Astrodevil** [comment]
You changed everything and made it more inconsistent. 

- Make Titles as previous, No need to change.
- Remove contributors section, It's not needed.
- Back to top, only needed at bottom section (use button shield)

- Remove these labels

1. closed issue
2. closed pull request
3. language
4. css
5. pull request

**Comment by ayush-sleeping** [comment]
> You changed everything and made it more inconsistent. 
> 
> - Make Titles as previous, No need to change.
> - Remove contributors section, It's not needed.
> - Back to top, only needed at bottom section (use button shield)
> 
> - Remove these labels
> 
> 1. closed issue
> 2. closed pull request
> 3. language
> 4. css
> 5. pull request
> 
> 

I am in College now , When I will reach home in the evening, I will complete this task....

**Comment by ayush-sleeping** [comment]
hey @Astrodevil , 
I have fixed all things , But I didn't understand the first point ( Tiles),
Kindly clarify me , So that I can fix it as soon as possible .

**Comment by Astrodevil** [comment]
> hey @Astrodevil , 
> 
> I have fixed all things , But I didn't understand the first point ( Tiles),
> 
> Kindly clarify me , So that I can fix it as soon as possible .

(Heading) Like previous

**Comment by ayush-sleeping** [comment]
> > hey @Astrodevil ,
> > I have fixed all things , But I didn't understand the first point ( Tiles),
> > Kindly clarify me , So that I can fix it as soon as possible .
> 
> (Heading) Like previous

Ooooo Got it , Any thing else you want , I will fix .........

**Comment by ayush-sleeping** [comment]
Hey @Astrodevil , Checkout now 
I have fixed headings
For Final Output Visit here : https://github.com/ayush-sleeping/ZeroOctave-Javascript-Projects/blob/main/README.md

**Pull request merged**
