### PR TITLE
Responsive Restaurant Menu Webpage

### PR DESCRIPTION
**Pull request by KshitizSharma11**
This is a Responsive Restaurant Food Menu that has animation effects in it Built Using HTML and CSS

In reference to #66

### CODE REVIEW

**Comment by NOiR-07** [comment]
Make a folder named restaurant and keep all files into that so that anyone can recognise them, also change the path of all files simultaneously 
eg. Restaurant folder and all files inside them

**Comment by Astrodevil** [comment]
@KshitizSharma11 Please provide screenshot of running project and explain! Will menu.html act as different project or only only affect restaurant project.

**Comment by KshitizSharma11** [comment]
well actually this menu here in this repository is integrated with the homepage so as to give a nice overview how it would 
look when actually integrated in a website .



**upon tapping menu on the restaurant homepage this menu can be accessed and it looks something like this**



**It can be used as a different project or can also be linked to the restaurant project as demonstrated here**
@Astrodevil @NOiR-07

**Review by Astrodevil — COMMENTED** [review]
This can be added. as folder is added for restaurant site

**Pull request merged**
