### PR TITLE
Pinterest extension for chrome browser

### PR DESCRIPTION
**Pull request by ranimanya**
### 👨‍💻 Changes proposed
I have added all the required files. 
Different folders have been created for html, css, js and images. 

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

All the files have to be collected in one folder for functioning of the project. I have tried to maintain the format in which they have to be added.
There are three folders - styles, scripts and images, they also contain a sub-folder 'pinterest-mock' along with other related files.
Other files namely board, options, popup and manifest do not need to be included in folders.

### 📷 Screenshots

https://imgur.com/a/j4ThGWa

https://imgur.com/a/CgNc5Vh 

https://imgur.com/a/KlM7NJb 

https://imgur.com/a/mRUiOqM

### CODE REVIEW

**Comment by NOiR-07** [comment]
your project is not functioning properly, please run the project on your local machine before making a pr

**Comment by ranimanya** [comment]
> your project is not functioning properly, please run the project on your local machine before making a pr

Okay, I'll rectify it.

**Comment by ranimanya** [comment]
https://user-images.githubusercontent.com/81632252/165092511-122c84b2-ab08-449c-a12b-655faed635c2.mp4

https://user-images.githubusercontent.com/81632252/165093996-6d2cd22c-264d-4db0-b1ac-688cf89f3cf6.mp4

Above videos are about the working of the project and it is functioning well...
Maybe I haven't committed files properly....can i create another pr?

Sorry for late reply...

**Comment by NOiR-07** [comment]
your css isn;t working too, u can make a new pr for the same issue and also We've changes the files for the website, so i suggest you to update your forked repo and add your project in cards.json and readme instead of index and cardsdata file

**Pull request closed without merging**
