### PR TITLE
News Website added

### PR DESCRIPTION
**Pull request by Aritra777**
### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by NOiR-07** [comment]
Add your website on index.html and cardsdata page of the website

**Comment by Aritra777** [comment]
@NOiR-07 I have added the website to index and cardsdata

**Comment by NOiR-07** [comment]
resolve the conflict in cardsdata.js file (first try to update your forked repo)

**Comment by Aritra777** [comment]
I have resolved the conflicts. @NOiR-07

**Comment by Aritra777** [comment]
Hii! @NOiR-07 its been 12days since I make this PR, kindly check and merge this. And if there is any error please inform me, I will definitely try to resolve that as soon as possible.

**Comment by NOiR-07** [comment]
> Hii! @NOiR-07 its been 12days since I make this PR, kindly check and merge this. And if there is any error please inform me, I will definitely try to resolve that as soon as possible.

sorry for the delay!! there is some conflict in index.html file, try to update your forked repo once again

**Comment by Aritra777** [comment]
@NOiR-07 conflict has resolved. Please Check now

**Comment by NOiR-07** [comment]
We've changes the files for the website, so i suggest you to update your forked repo and add your project in cards.json and readme instead of index and cardsdata file

**Comment by Aritra777** [comment]
@NOiR-07  I have some conflict in my repo so I have to make a new a new PR and thats why I am closing this PR and will make a new one.

**Pull request closed without merging**
