### PR TITLE
CSS Unit converter

### PR DESCRIPTION
**Pull request by Kumar-Ankit56**
### 👨‍💻 Changes proposed

This is project-based on CSS unit conversion under the reference of issue no https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues/430. Like main functionality of this project is when you will give value in Pixel then it will convert in em and vice versa.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Screenshot (120)

### CODE REVIEW

**Comment by NOiR-07** [comment]
your css file isn't working and add your project in the index and cardsdata file of website

**Comment by Kumar-Ankit56** [comment]
@NOiR-07 buddy, I commit the changes as you have suggested kindly review it and merge this Pr.

**Comment by Palaksharma23** [comment]
@Kumar-Ankit56 css and js files are still not linked properly 
use ```../assets/css/Pixel converter.css```

**Comment by Kumar-Ankit56** [comment]
@Palaksharma23 Hope so it will work now.

**Comment by NOiR-07** [comment]
We've changes the files for the website, so i suggest you to update your forked repo and add your project in cards.json and readme instead of index and cardsdata file

**Comment by Kumar-Ankit56** [comment]
I'm closing this due to the lots of overcrowded files and it gets messed up with this pr after closing this I'm going to create a new fresh Pr for my assigned issue.

**Pull request closed without merging**
