### PR TITLE
Now we can navigate within same webpage using navigation bar

### PR DESCRIPTION
**Pull request by ravish036**
### Screenshots 
image

image

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

please consider this contribution under ssoc'22.

### CODE REVIEW

**Comment by myhacktech** [comment]
@ravish036 add a preview or screenshot of ur work to help us understand better

**Comment by ravish036** [comment]
> @ravish036 add a preview or screenshot of ur work to help us understand better

Done

**Review by myhacktech — DISMISSED** [review]

**Comment by myhacktech** [comment]
@Astrodevil to be merged

**Comment by Astrodevil** [comment]
solve the conflicts

**Comment by ravish036** [comment]
> solve the conflicts

done

**Review by Astrodevil — APPROVED** [review]

**Pull request merged**
