### PR TITLE
Added Stopwatch Application

### LINKED ISSUE #428: Stopwatch
**Project Description :** 
A stopwatch application with proper 'Start', 'Stop' and 'Reset' buttons. 

**Tech Stack :** 
HTML, CSS and Javascript. 

**Project Preview :** 
stopwatch

I'd like to contribute under GSSOC22 .

### PR DESCRIPTION
**Pull request by debadrita612**
### 🛠️ Fixes Issue (Number)

Closes #428 

### 👨‍💻 Changes proposed
Stopwatch Application added. 

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
The stopwatch application works completely fine. Tech stack used : HTML , CSS and Javascript. Did DOM manipulation, used event listeners and functions. Added proper functional 'Start', 'Stop' and 'Reset' buttons. 

### 📷 Screenshots

stopwatch_

### CODE REVIEW

**Comment by NOiR-07** [comment]
resolve the conflict in cardsdata.js file (first try to update your forked repo)

**Comment by debadrita612** [comment]
@NOiR-07 updated my forked repo.. please check

**Comment by debadrita612** [comment]
@NOiR-07 if there is still a conflict in cardsdata.js file.. could you please tell me what is it?

**Comment by debadrita612** [comment]
@NOiR-07 could you please mention what is the conflict in cardsdata.js file?

**Comment by NOiR-07** [comment]
conflict is in index.html, try once to update that

**Comment by debadrita612** [comment]
@NOiR-07 updated index.html file. Please check and let me know.

**Pull request merged**
