### PR TITLE
Hacktoberfest logo was not visible.

### PR DESCRIPTION
**Pull request by trishitchar**
Fixed this issue.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by trishitchar** [comment]
Before - Logo is not visible

**Comment by trishitchar** [comment]
Before and after
After fixing the issue

**Review by Astrodevil — APPROVED** [review]

**Comment by trishitchar** [comment]
@Astrodevil @myhacktech
Hey can you guys put hacktoberfest level on it.
Thank you.

**Comment by trishitchar** [comment]
Hey!!!
Please put a lebel on it so it'll be counted on hacktoberfest

**Pull request merged**
