### PR TITLE
Added Movie/TV Series Quote Generator (fixed issue #427)

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
### 👨‍💻 Changes proposed

Added Movie/TV Series Quote Generator which generates random quote along with Movie/TV series name it comes from and the name of the character who said it. There is also a feature of sharing the generated quote via WhatsApp and Twitter.

### ✅ Check List (Check all the applicable boxes) 

- [X] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [X] This PR does not contain plagiarized content.
- [X] My Addition/Changes works properly and matches the overall repo pattern.
- [X] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Screenshot_2022-04-02-17-01-47-209_com android chrome
Screenshot_2022-04-02-17-02-27-897_com android chrome

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
Hi @sreelakshmig009 kindly look into my PR and let me know if any change is required

**Comment by sreelakshmig009** [comment]
> Hi @sreelakshmig009 kindly look into my PR and let me know if any change is required

Hi @abhilipsasahoo03 just one change

image

Can you increase the spacing of the heading and the extensible division containing the quote?

**Comment by abhilipsasahoo03** [comment]
> > Hi @sreelakshmig009 kindly look into my PR and let me know if any change is required
> 
> Hi @abhilipsasahoo03 just one change
> 
> image
> 
> Can you increase the spacing of the heading and the extensible division containing the quote?

Okay sure.

**Comment by abhilipsasahoo03** [comment]
Hi @sreelakshmig009 I've tried to make it responsive. Check below demo:


https://user-images.githubusercontent.com/80174214/161385477-49ca45f9-24e8-4b14-b145-c8abeb9dd332.mp4

**Comment by abhilipsasahoo03** [comment]
Hi @sreelakshmig009 I've made the appropriate changes and made it responsive so that the text doesn't overflow on mobile screen size. Check below demo:

**Pull request merged**
