### PR TITLE
Coin-Toss-Game

### LINKED ISSUE #561: Coin-Toss-Game
Feature Description
A coin toss game that tells you weather you have got heads or tails at a time. This issue is under GSSoC'22 Contributions.

Steps Followed✅

Check the box with [x] If you followed all the steps.

-[ ] Is your feature request related to a problem? Please describe.
-[x] Describe the solution you'd like
-[ ] Describe alternatives you've considered
-[ ]Additional context

Code of Conduct✅

-[x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
-[x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
-[x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

### PR DESCRIPTION
**Pull request by Pratham-R**
### 🛠️ Fixes Issue (#561)
Closes #561 

### 👨‍💻 Changes proposed

Added a Coin Toss Game

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
Screenshot 2022-04-30 at 9 28 37 PM

### CODE REVIEW

**Comment by NOiR-07** [comment]
remove the useless files which are not related to project

**Comment by Pratham-R** [comment]
Please check now. @NOiR-07

**Comment by Astrodevil** [comment]
Json and README is not properly updated. Please follow proper order.

**Comment by Pratham-R** [comment]
Is it working now? @NOiR-07

**Comment by Pratham-R** [comment]
I have resolved the issue. Sorry for the delay. @Astrodevil

**Comment by Astrodevil** [comment]
update your fork and make correction project section of README @Pratham-R asap

**Pull request merged**
