### PR TITLE
#13 Landing page 

### PR DESCRIPTION
**Pull request by SO1ee**
This Landing page is responsive and i have added javascript applications(e.g analog_clock , auto_write_text ,calculator ,digital_clock ,color_flipper etc) on individual cards so when someone  will land on our landing page at a glimpse he/she will be able to know about our javascript applications and on that landing page he/she will be able to perform some task like
Screenshot 2021-10-01 213741
 check time , calculate ,check weather etc.

### CODE REVIEW

**Comment by NOiR-07** [comment]
@SO1ee Mention the issue tag

**Comment by SO1ee** [comment]
#13

**Review by Astrodevil — CHANGES_REQUESTED** [review]
Put this landing page .html, .css, .js outside the folder.  It will be easier for anyone to add there project to reflect on landing page

**Comment by SO1ee** [comment]
In this landing page i have used previously done javascript files and added some additional css file ,now those css files are outside of the folder .Next time when some one need to make any changes all she /he has to  do is to create some cards and add some css files to design those cards.

**Comment by Astrodevil** [comment]
> 
> 
> In this landing page i have used previously done javascript files and added some additional css file ,now those css files are outside of the folder .Next time when some one need to make any changes all she /he has to do is to create some cards and add some css files to design those cards. index.html page is our landing page and it is outside of folders

I said only put main html or css or js file outside! which is the main one that runs the landing page this makes mess, 

please look for refrence here: https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects

**Comment by SO1ee** [comment]
Okay sir! I need some time .

**Comment by Astrodevil** [comment]
> Okay sir! I need some time .

No hurry, you can do on your own pace🙌🏼

**Comment by SO1ee** [comment]
Hello sir! I have removed all internal csss and javascript from the landing page which were creating mess . Now the landing page is clean and only html tags are there .

**Comment by Astrodevil** [comment]
analog_clock1.js and auto-write-text1.js is still there. Is that required? please confirm.

**Comment by SO1ee** [comment]
Yes sir both of them are required.

**Review by Astrodevil — APPROVED** [review]

**Pull request merged**
