### PR TITLE
Book type button click fix

### PR DESCRIPTION
**Pull request by rtewari056**
### 👨‍💻 Changes proposed
1. Book Type label added.
2. Type of book is now clickable.
3. Formatted entire code base for better indentations.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
[Deployment link](https://zerooctave.github.io/ZeroOctave-Javascript-Projects/Public/BooksLibrary.html)

library

### CODE REVIEW

**Comment by myhacktech** [comment]
as i can see in original website,it is clickable already

**Comment by myhacktech** [comment]
@Astrodevil

**Comment by rtewari056** [comment]
> as i can see in original website,it is clickable already

It is not clikable if you try to click on the names

**Comment by myhacktech** [comment]
> > as i can see in original website,it is clickable already
> 
> It is not clikable if you try to click on the names

yeah ..in that way

**Review by myhacktech — APPROVED** [review]

**Comment by myhacktech** [comment]
> > as i can see in original website,it is clickable already
> 
> It is not clikable if you try to click on the names

do attach link along with screenshot,it is must

**Comment by rtewari056** [comment]
Done @myhacktech

**Comment by myhacktech** [comment]
> > > as i can see in original website,it is clickable already
> > 
> > 
> > It is not clikable if you try to click on the names
> 
> do attach link along with screenshot,it is must

@Astrodevil review or merge this

**Review by Astrodevil — APPROVED** [review]

**Pull request merged**
