### PR TITLE
Dash board website

### LINKED ISSUE #949: Addition of new project
Can I add a new project in it ??

### PR DESCRIPTION
**Pull request by intozen**
### 🛠️ Fixes Issue (Number)

Fixes #949 

### 👨‍💻 Changes proposed

- Created a Dash Board Website
- Created a new barnch
- proposed changes to the branch
- Created a PR

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

Please merge this PR. I am a very beginner in Open Source And Web Dev.

### 📷 Screenshots

image

### CODE REVIEW

**Comment by intozen** [comment]
please check and merge.

**Comment by Astrodevil** [comment]
Files are not arranged properly according to this repo. Please do that.

**Comment by intozen** [comment]
Yes, I have renamed and arranged the files based on the conventions. Please lemme know if anything else is needed.

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
- Arrange the files according to the structure of the repository.
> Html files are in public, and other files are in asset folder in root directory with respective categories.

**Pull request closed without merging**
