### PR TITLE
Added  find key game

### PR DESCRIPTION
**Pull request by deep-69bits**
### 👨‍💻 Changes proposed

- Added find key game

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
I am a gssoc 2022 participant 

### 📷  Video

https://user-images.githubusercontent.com/96793524/159363857-15bf5cac-1846-4595-ab98-a8810e9d018b.mp4

### CODE REVIEW

**Comment by NOiR-07** [comment]
image
This is how is it working on my local machine, recheck on your machine and fix it

**Comment by deep-69bits** [comment]
ok i will check

**Comment by Astrodevil** [comment]
Last few days remaining, Complete your work till 31st.

**Comment by Astrodevil** [comment]
@deep-69bits  You still have time till evening. After that I will be closing this PR.

**Pull request closed without merging**
