### PR TITLE
Added missing project

### LINKED ISSUE #615: Add Missing project
Add #582 in cards.json and README (Put this at no. 12 by editing previous music app)

### PR DESCRIPTION
**Pull request by shrey2003**
### 🛠️ Fixes Issue

Closes #615 

### ✅ Check List (Check all the applicable boxes) 

- [✅] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [✅] This PR does not contain plagiarized content.
- [✅] My Addition/Changes works properly and matches the overall repo pattern.
- [✅] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by shrey2003** [comment]
I am a GSSoC'22 participant

**Comment by Astrodevil** [comment]
You don't need to create folder for 1 image. Please make correction, image is not properly rendered.
Screenshot 2022-04-21 172357

**Comment by shrey2003** [comment]
@Astrodevil corrected

**Comment by Astrodevil** [comment]
> @Astrodevil corrected

Photo is still not apearing

**Comment by shrey2003** [comment]
@Astrodevil Please add GSSoC'22 labels as I am a participant

**Comment by Astrodevil** [comment]
As it is very basic addition. Tags are already added in issue.

**Pull request merged**
