### PR TITLE
added a new file i.e., Word_Definition

### PR DESCRIPTION
**Pull request by abhinay99190**
I am added Word Definition web app...!

<hr>

**### Word Definition**

_The Word Definition app will show the definition of the following words._

<hr>

**### Tech Stack**

> **### Client:--**

 HTMLCSSJAVASCRIPT

<hr>

**### API Reference**

**_API:--_** [MERRIAM-WEBSTER'S DEVELOPER CENTER](https://dictionaryapi.com/)

<hr>

## Screenshots / Gif (Optional) 📸

**### _In the first image we can see that when we type correct words we can see their definition what the word means._**

img 1<hr>

**### _In the second image we can that when we type wrong words it suggested me the correct word._**

img 2<hr>

**### _In the third image we can  that when we type random words it gives "no result found" _**

img 3

**###By Abhinay singh_**

### CODE REVIEW

**Comment by NOiR-07** [comment]
Specify the issue no that was assigned to you

**Comment by abhinay99190** [comment]
added a new file i.e., Word_Definition #292

**Comment by NOiR-07** [comment]
> added a new file i.e., Word_Definition #292

this is your pr tag no, issue no is different
take care of it from next time

**Comment by abhinay99190** [comment]
Thanks sir for giving me this opportunity to work with you....

**Pull request merged**
