### PR TITLE
Tourist Website Added

### PR DESCRIPTION
**Pull request by samipak458**
### 👨‍💻 Changes proposed
Project Tourist Website Added

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
It is  fully responsive having beautiful animation. Have a look my website: [Tourist](https://merapakistan.samimunir2002.repl.co/)

### 📷 Screenshots
image

### CODE REVIEW

**Comment by samipak458** [comment]
@Astrodevil kindly review and merge my PR. Thank you.

**Comment by samipak458** [comment]
All the required changes has been made. @Astrodevil kindly review and merge it.

**Comment by Astrodevil** [comment]
Please try to squash all commits into one, Fix these errors.

**Comment by Astrodevil** [comment]
Don't bother about README. Fix the main works

**Comment by samipak458** [comment]
@Astrodevil I rechecked complete project and it's working completely fine on local. There is no issue in it. I don't know why it's on working here.

**Comment by Astrodevil** [comment]
Okh, Let's check again

**Comment by Astrodevil** [comment]
> @Astrodevil I rechecked complete project and it's working completely fine on local. There is no issue in it. I don't know why it's on working here.

Actually first page was working fine but about and gallery throwing above errors, We will check it again

**Comment by samipak458** [comment]
> > @Astrodevil I rechecked complete project and it's working completely fine on local. There is no issue in it. I don't know why it's on working here.
> 
> Actually first page was working fine but about and gallery throwing above errors, We will check it again

ok

**Comment by NOiR-07** [comment]
image

@samipak458 I've reviewed too on my local machine and it isn't working, check if there is some spell error or some wrong directory given.
also update your forked repo too.

**Comment by samipak458** [comment]
Ok, I am creating another PR. I think there is some issue in directory.

> image
> 
> @samipak458 I've reviewed too on my local machine and it isn't working, check if there is some spell error or some wrong directory given. also update your forked repo too.

**Pull request closed without merging**
