### PR TITLE
Added Movie Search App

### PR DESCRIPTION
**Pull request by Atif0604**
### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

image

### CODE REVIEW

**Comment by Astrodevil** [comment]
Update your project on README

**Comment by Atif0604** [comment]
> Update your project on README

Done
@Astrodevil

**Comment by Atif0604** [comment]
Hey @Astrodevil Please add Labels to this

**Comment by Atif0604** [comment]
Hey @Astrodevil Please add  Labels to this PR

**Comment by Astrodevil** [comment]
If you are contributing for the program you have to mention it in issue or PR.

**Pull request merged**
