### PR TITLE
Rain Effects

### PR DESCRIPTION
**Pull request by SAMRIDHISINHA**
Hello, I am Samridhi(GGSOC'22 contributor) and have created a javascript project with rainy effects in the background.

### ✅ Check List (Check all the applicable boxes) 

- [ ✅] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [ ✅] This PR does not contain plagiarized content.
- [ ✅] My Addition/Changes works properly and matches the overall repo pattern.
- [✅ ] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

RainEffects

### CODE REVIEW

**Comment by SAMRIDHISINHA** [comment]
Please add GGSOC label.

**Comment by NOiR-07** [comment]
mention ur issue number

**Comment by SAMRIDHISINHA** [comment]
Issue number #682

**Comment by SAMRIDHISINHA** [comment]
Why is the pull request not created?

**Comment by SAMRIDHISINHA** [comment]
Why is the pull request not merged?

**Comment by NOiR-07** [comment]
The project is working fine just add your project in cards.json and readme file of the website
and don't make multiple pr for one issue

**Comment by SAMRIDHISINHA** [comment]
@Astrodevil 
Please add the updated Readme file

[README.md](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/files/8800165/README.md)

**Comment by SAMRIDHISINHA** [comment]
errror
Can you please tell me where is the option to create new files(Readme,cards.json)
While pushing,error 403 is encountered
Please help
@Astrodevil

**Comment by Astrodevil** [comment]
You have to find readme and cards.json files in forked/clone repository and make changes from there.

**Comment by Astrodevil** [comment]
@SAMRIDHISINHA  You still have time till evening. After that I will be closing this PR.

If you have a issue related to addition of json and README. Just update your fork. I will do it by my side.

**Comment by SAMRIDHISINHA** [comment]
@Astrodevil Please check once.

**Pull request merged**
