### PR TITLE
Sneaker site files added

### PR DESCRIPTION
**Pull request by Adit0507**
### 🛠️ Fixes Issue (Number)
#215 

### ✅ Check List (Check all the applicable boxes) 

- [c] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by NOiR-07** [comment]
there is some conflict please resolve it

**Comment by Adit0507** [comment]
> there is some conflict please resolve it

When I raised this PR, there was no conflict with the base branch and it could be merged with no problem, now I dont know why there is a conflict

**Comment by Adit0507** [comment]
The conflict is resolved, kindly merge it now

**Comment by Astrodevil** [comment]
Still there are some conflicts, Please solve it

**Comment by Astrodevil** [comment]
Why you closed this issue?

**Pull request closed without merging**
