### PR TITLE
Added a new automatic image slider animation project

### PR DESCRIPTION
**Pull request by Palaksharma23**
I have added a new project which changes background image automatically and it can be used to give scrolling image animation effects to a website .

### CODE REVIEW

**Comment by NOiR-07** [comment]
@Palaksharma23 please attach a screenshot of the project while running it on the live server, so that we can verify it.

**Comment by Palaksharma23** [comment]
https://user-images.githubusercontent.com/87171452/144710711-ef52294a-e6f9-4b7e-a1aa-b1525cec10b2.mp4

**Comment by Palaksharma23** [comment]
@NOiR-07 sure sir from next time i will do that along with pull request .

**Comment by NOiR-07** [comment]
@Palaksharma23 all good 👍

**Pull request merged**
