### PR TITLE
Personal portfolio Website Using Html & CSS

### PR DESCRIPTION
**Pull request by iashupandey**
Simple and Impressive Single page portfolio

### CODE REVIEW

**Comment by NOiR-07** [comment]
@iashupandey Provide the screenshots of your projects for overview

**Comment by iashupandey** [comment]
Sure.. I'll provide

**Comment by iashupandey** [comment]
I had added the screenshot and also updated the code.

**Comment by NOiR-07** [comment]
@iashupandey Don't make a separate image folder, put all the images in the assets/Images folder and remove the portfolio folder too

**Comment by iashupandey** [comment]
Sure, will do that.

**Review by Astrodevil — COMMENTED** [review]
I am closing this PR now.

**Pull request closed without merging**
