### PR TITLE
Closes  #968   url-shortner-added

### LINKED ISSUE #968: Add a URL_Shortner project
**Is your feature request related to a problem? Please describe.**
I want to contribute our group's URL_Shortner project to this repository as a part of our coursework for OpenSource Lab

**Describe the solution you'd like**
Our project provides short url for long one

**Additional context**
Project Link: https://github.com/madhhuurrii/URL-Shortner

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ ] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

### PR DESCRIPTION
**Pull request by ShreeveshKumar**
### 🛠️ Fixes Issue (#968 )

Closes #issue_number 

 #968 

### 👨‍💻 Changes proposed

Added the url-shortner website its html,css,js and images 

### ✅ Check List (Check all the applicable boxes) 

- [✅ ] You have linked this PR to the correct issue.
- [✅ ] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [✅ ] This PR does not contain plagiarized content.
- [✅] My Addition/Changes works properly and matches the overall repo pattern.
- [✅ ] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

 you will need to put your own API_KEY
 #968 need to be merged

### 📷 Screenshots

image

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
Please add a video of its working, I won't be able to review the code properly. If it works, then I will merge it.

**Comment by ShreeveshKumar** [comment]
> Please add a video of its working, I won't be able to review the code properly. If it works, then I will merge it.

sure here it is ... 

https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/assets/115733778/fc62dd65-a118-4336-b7ea-d1299e12216e

**Review by Anmol-Baranwal — COMMENTED** [review]
@ShreeveshKumar 

Even removing .gitignore and package.json won't fix the issue.

Since, it is clearly specified the strict tech stack of projects in the codebase.

> Contributing guidelines
image

This won't run on the website, as per the backend structure.

What is the number of requests allowed and can the api key be exposed?

**Comment by ShreeveshKumar** [comment]
No abt the API key and the limit is 1000/month

**Comment by Anmol-Baranwal** [comment]
I don't think, this will properly work once hosted on the deployed link.

So, I will not be able to merge this. This is clearly specified in the contributing guidelines as well.

**Comment by ShreeveshKumar** [comment]
ok no worries

**Comment by Anmol-Baranwal** [comment]
> ok no worries

Thanks for understanding.

If you want to contribute, you can visit Linkshub. I'm the maintainer there. Just comment on issue with tag `up for grabs` and I will assign you one.

**Comment by ShreeveshKumar** [comment]
oh thank you so much ! I would love to contribute to amazing open-source projects and join the open-source community : )

**Comment by Anmol-Baranwal** [comment]
Closing due to above mentioned reason.

**Pull request closed without merging**
