### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by YashAryanTheCoder**
## Proposed Changes
- Added some amazing features in calculator
- Improved the CSS of ***index.html***
- Corrected the typos
- Made the calculator more interactive 
Edit 1

### CODE REVIEW

**Comment by Astrodevil** [comment]
The main aim of landing page enhancement is to make it easier for everyone to add new projects. Consider moving CSS and js codes in a separate file. Try to make it like a small snippet for each new project, so that new contributors can understand and add new snippets for their project to get onto the landing page. 

**Could you do that?**

**Comment by YashAryanTheCoder** [comment]
Yes, I will try to move CSS and js codes in separate files and make it like a small snippet for each new project.

**Comment by Astrodevil** [comment]
@YashAryanTheCoder Go Ahead! Make sure to squash all commits into 1 PR. Take your time.

**Comment by Astrodevil** [comment]
> Yes, I will try to move CSS and js codes in separate files and make it like a small snippet for each new project.

Are you working on this? or I can assign someone else

**Comment by YashAryanTheCoder** [comment]
I am working on it

**Pull request closed without merging**
