### PR TITLE
Added convert fonts

### PR DESCRIPTION
**Pull request by ritikranjan12**
All files had been Updated.

### CODE REVIEW

**Comment by NOiR-07** [comment]
mention issue number

**Comment by ritikranjan12** [comment]
I had Added the Project Convert Fonts in context with the previously made pull request #212 which I had closed due to some errors.

**Comment by NOiR-07** [comment]
pls update your forked repo to remove the conflicts

**Comment by NOiR-07** [comment]
MAke a new pr, closing this now!

**Pull request closed without merging**
