### PR TITLE
Added Color Code Converter Files

### LINKED ISSUE #223: Add a color code converter JS app
**Is your feature request related to a problem? Please describe.**

It's a JS app that converts from and to different color representation codes like RGB, Hex, HSL, HWB, CMYK, ..etc.

**Additional context**

Gonna make use of HTML, CSS, & JS.

### Steps Followed✅

- [x] Is your feature request related to a problem? Please describe.
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

### PR DESCRIPTION
**Pull request by XZANATOL**
### 🛠️ Fixes Issue #223 

fixes #223 

### 👨‍💻 Changes proposed

Added Color Code Converter Files

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Capture

### CODE REVIEW

**Comment by XZANATOL** [comment]
@NOiR-07 any updates about the review?

**Comment by NOiR-07** [comment]
Don't make a separate folder, keep ur html file in public and rest in assets

**Comment by XZANATOL** [comment]
@NOiR-07 Done.

**Comment by NOiR-07** [comment]
Can you add an example how to add colour name as simply writing red or something isn't working
how people would know what to write there

**Comment by XZANATOL** [comment]
Got your point, ok give me a couple of mins and will make a new commit.

**Comment by XZANATOL** [comment]
@NOiR-07 Done.

**Comment by NOiR-07** [comment]
Yeah looks good, also add your project in index file of website

**Pull request merged**
