### PR TITLE
added find key game

### PR DESCRIPTION
**Pull request by deep-69bits**
### 👨‍💻 Changes proposed
I have added a find key game 

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

I have used HTML  CSS and vanilla JS
I am gssoc 2022 participant

### 📷 Video

https://user-images.githubusercontent.com/96793524/158789013-ff4c509a-cd01-43a5-ba62-463a25697abb.mp4

### CODE REVIEW

**Comment by deep-69bits** [comment]
Can anyone tell me how to be level 2 or 3??

**Comment by Astrodevil** [comment]
> Can anyone tell me how to be level 2 or 3??

It depends on your small or big contribution.

**Comment by deep-69bits** [comment]
> > Can anyone tell me how to be level 2 or 3??
> 
> It depends on your small or big contribution.

merge please

**Comment by Astrodevil** [comment]
Link the Issue assigned regarding this PR and also add this new project in index.html

**Comment by deep-69bits** [comment]
> Link the Issue assigned regarding this PR and also add this new project in index.html

ok

**Pull request closed without merging**
