### PR TITLE
Type Writer Effect Js

### PR DESCRIPTION
**Pull request by nouraan-ahmed**

### CODE REVIEW

**Comment by Astrodevil** [comment]
@nouraan-ahmed to do list already exists in this repo, Please push files for Type Writer Effect according to repo structure not in a folder.

**Comment by nouraan-ahmed** [comment]
Okay Done @Astrodevil

**Comment by nouraan-ahmed** [comment]
Done @Astrodevil

**Comment by nouraan-ahmed** [comment]
The pull request is accepted but not calculated as a PR in gssoc leaderboard

**Comment by Astrodevil** [comment]
You didn't created any issue or mentioned the contribution for gssoc earlier.

**Pull request merged**
