### PR TITLE
Add Guess The Number Game

### LINKED ISSUE #184: Add Guess the Number game
I would like to add a JS game _Guess the Number_ which will make use of some JS concepts like:

1. DOM manipulation
2. Event listeners
3. Handling click events

### PR DESCRIPTION
**Pull request by devgirlcodes**
### 🛠️ Fixes Issue (Number)

Fixes #184 

### 👨‍💻 Changes proposed

Add the Guess the Number game and it's card on the landing page.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
guess-the-number

### CODE REVIEW

**Comment by NOiR-07** [comment]
what changes have you done in index.html?

**Comment by devgirlcodes** [comment]
> what changes have you done in index.html?

@NOiR-07 I added the card for guess the number game and pulled the changes made on the landing page from #209

**Comment by NOiR-07** [comment]
You've made so much changes in index file, you just had to add one card class for your project.

**Comment by devgirlcodes** [comment]
@NOiR-07 that's because of my editor. It formats the document on saving.

**Comment by NOiR-07** [comment]
Can't merge this one instead you can make a new pr and leave the index part
that we'll do it later

**Pull request closed without merging**
