### PR TITLE
The "Candy Store" item is not clickable and the image in "Color game" is invisible

### PR DESCRIPTION
**Pull request by zugzwang03**
### 👨‍💻 Changes proposed
The candy store icon was not clickable, but then I fixed that issue now.
The image in color game was invisible but I fixed it now.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
I have resolved this issue under SSOC'22.

### 📷 Screenshots

Issue no. #795 
Previously it was :
bug
Now after fixation : 
fixedit

Issue no. #810
Previously it was :
bug
Now after fixation:
colorgame

### CODE REVIEW

**Comment by zugzwang03** [comment]
https://zugzwang03.github.io/ZeroOctave-Javascript-Projects/ is how the website functions now.

**Review by myhacktech — DISMISSED** [review]

**Comment by zugzwang03** [comment]
Can @Astrodevil please review this PR?

**Comment by zugzwang03** [comment]
Since even after 7 days this PR was not merged, I linked another issue with the same PR. @Astrodevil @myhacktech

**Review by myhacktech — APPROVED** [review]

**Comment by Astrodevil** [comment]
You have done so many changes for just 2 small bugs, don't move files by changing names. Please leave files as it is. I am closing this PR make new one.

**Pull request closed without merging**
