### PR TITLE
Added Color Game

### PR DESCRIPTION
**Pull request by Whizz76**
Added RGB Game
issue number #492 
r1

r3
r2

### CODE REVIEW

**Review by Astrodevil — COMMENTED** [review]
Wrong addition, please make this correct.

**Comment by Whizz76** [comment]
Have made the changes, please review it

**Comment by Whizz76** [comment]
changed ref link names in index.html

**Comment by Whizz76** [comment]
further changed

**Comment by NOiR-07** [comment]
update your forked repo once

**Comment by Astrodevil** [comment]
You have done multiple commits. please make a Fresh PR with proper changes.

**Pull request closed without merging**
