### PR TITLE
Piyush

### PR DESCRIPTION
**Pull request by rajpiyush4**
### 👨‍💻 Changes proposed
1. Width changing of the images of all the cards on hover caused stretching of images so removed it and added some::before element animation and also changed the position of images in all cards to be in the middle of header-name and view button.
2. Removed background-color changing of the navbar on scroll in JS file not causing any code break, it looks good now after I changed the colors.
3. And did some centering of some uncentered elements like in navbar(ul was not vertically aligned in the center ) and in cards-container ( align-items was not in the center)
4. 
### ✅ Check List (Check all the applicable boxes) 

- [✓ ] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [✓ ] This PR does not contain plagiarized content.
- [✓ ] My Addition/Changes works properly and matches the overall repo pattern.
- [✓ ] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Screenshot (82)

### CODE REVIEW

**Comment by Astrodevil** [comment]
You have done good improvements, Please try to improve the loading page also.

**Comment by rajpiyush4** [comment]
Ok, I'll try.

**Comment by rajpiyush4** [comment]
hey, check this out:
[zeroOctave.webm](https://user-images.githubusercontent.com/86086085/180305693-a675b1ba-45d8-46ce-99d9-55b35bd73607.webm)

**Comment by Astrodevil** [comment]
it's not working

**Comment by rajpiyush4** [comment]
I've tried again and it's working.
it's a video, did you play it?

**Comment by rajpiyush4** [comment]
I've tried again and it's working.
btw it's a video, have you tried to play it?

**Comment by Astrodevil** [comment]
> hey, check this out: [zeroOctave.webm](https://user-images.githubusercontent.com/86086085/180305693-a675b1ba-45d8-46ce-99d9-55b35bd73607.webm)

Any new update?

**Pull request merged**
