### PR TITLE
backend setup

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
### 👨‍💻 Changes proposed

1. Build the Backend
2. Separate Out Backend And Frontend. So that no clash happen in future (Earlier whole javascript was written in .html page, that was kinda ugly thing )
3. JSON file is create where all the projects data in placed, we are fetching that data to display on landing page

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

Every Project is listed there now. They all have their own image in the card and yes when click on card they redirect you to the projects

### 📷 Screenshots

sample

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@Astrodevil Please review

**Review by Astrodevil — CHANGES_REQUESTED** [review]
Some images and links are not working properly. Please add every project on the page so that only new ones need to be added. Looks like **cardsData.js** file is not necessary? if yes delete it.

- Change themes as discussed before.

**Comment by Abh1shekSingh** [comment]
@Astrodevil  Some images are not visible cause, Contributers who added this project, has not provided images of their projects

**Comment by Astrodevil** [comment]
> @Astrodevil Some images are not visible cause, Contributers who added this project, has not provided images of their projects Also, Can you please tell me which links are not working ?

Please add images by your side by taking screenshots. Fix everything also add every single project from the repo and change theme related to **Organization logo** use [this](https://imagecolorpicker.com/en) site for picking color palette.

Every other changes made by you are good.

**Broken links**
- color chooser
- email validator
- github profiles
- Mapty
& some links are broken inside the project ( If you came across this type of error, consider raising issue or just mention a list so that other can work on that to fix it.)

**Comment by Abh1shekSingh** [comment]
@Astrodevil Please Take a look now. Changes Done
1. Theme Changed to org logo
2. Fixed Broken Links 
3. Mapty has some inside project broken links, which I fixed it.

**Pull request merged**
