### PR TITLE
Added a code to reviews section of a webite using javascript

### PR DESCRIPTION
**Pull request by Palaksharma23**
https://user-images.githubusercontent.com/87171452/145718561-84e3fe16-dde8-4f08-931f-fcc32d1fa1d1.mp4

### CODE REVIEW

**Comment by NOiR-07** [comment]
@Palaksharma23 please change the file location of CSS to assets/CSS and js to assets/js

**Comment by Palaksharma23** [comment]
Sure sir @NOiR-07

**Comment by Palaksharma23** [comment]
@NOiR-07 done sir

**Comment by Astrodevil** [comment]
@Palaksharma23 Why are you making a folder inside the Public folder, It is only for html files. I have seen there are photos inside reviews folder. There are already image and music folders inside the assets directory...

Please make corrections in all new PR.🎉

**Review by Astrodevil — CHANGES_REQUESTED** [review]
@Palaksharma23 Why are you making a folder inside the Public folder, It is only for html files. I have seen there are photos inside reviews folder. There are already image and music folders inside the assets directory...

Please make corrections in all new PR accordingly.🎉

**Comment by Palaksharma23** [comment]
ohh okay sir @Astrodevil :)

**Comment by Palaksharma23** [comment]
Sir can you merge all these new prs and then i will make a single pr changing location of files.

**Comment by Astrodevil** [comment]
> Sir can you merge all these new prs and then i will make a single pr changing location of files.

@NOiR-07 Please consider this.

**Comment by Palaksharma23** [comment]
> > Sir can you merge all these new prs and then i will make a single pr changing location of files.
> 
> @NOiR-07 Please consider this.

yes sir as there are 3 more folders in public

**Comment by NOiR-07** [comment]
@Palaksharma23 Can you please re run the code on machine and check as i can't see the css working on my machine
image

**Comment by Palaksharma23** [comment]
@NOiR-07 sir please once check it now

**Comment by NOiR-07** [comment]
> @NOiR-07 sir please once check it now

Still, same issue @Astrodevil can you please check it once and run it on your local machine.

**Comment by Astrodevil** [comment]
> > @NOiR-07 sir please once check it now
> 
> Still, same issue @Astrodevil can you please check it once and run it on your local machine.

Running fine in my machine you can merge it.

**Pull request merged**
