### PR TITLE
Added Joke Generator Chrome Extension

### PR DESCRIPTION
**Pull request by Atharv-110**
### 🛠️ Fixes Issue #213

Joke Generator Chrome Extension

### 👨‍💻 Changes proposed

1. Jokes Generator Chrome/Browser Extension Added.
2. Jokes Generator Application also included.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

1. README file added for the steps to load extensions on other PCs.

### 📷 Screenshots
JokeExtensionDemo

### CODE REVIEW

**Comment by Atharv-110** [comment]
#### Hey @NOiR-07 , I have raised my PR. Please do review it.

**Comment by NOiR-07** [comment]
there is some conflict please resolve it, I think you changed the indentation or something

**Comment by Atharv-110** [comment]
I've looked into that please guide me what actually that conflict is so that I will resolve it asap?

**Comment by Atharv-110** [comment]
@NOiR-07 now please review it

**Review by Astrodevil — COMMENTED** [review]
Follow the naming pattern of this repo, and move your files to respective folders (put json in js folder) Also add your project in index.html  by adding comment.

**Comment by NOiR-07** [comment]
Please update your forked repo once

**Comment by Atharv-110** [comment]
Sure within a day, I will be updating it.

**Comment by Atharv-110** [comment]
@NOiR-07 @Astrodevil May I raise a new PR as it has become a lot of mess in my forked, ig doing fresh would be more easy and smooth process.

**Comment by NOiR-07** [comment]
> @NOiR-07 @Astrodevil May I raise a new PR as it has become a lot of mess in my forked, ig doing fresh would be more easy and smooth process.

yes sure

**Pull request closed without merging**
