### PR TITLE
Tracker Expense Caclulator added

### PR DESCRIPTION
**Pull request by KiranAminPanjwani**
### 👨‍💻 Changes proposed

- I have added my project to your repository.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

- This project will help learners to learn Js functions and other concepts.
- This project will help learners to implement responsiveness using CSS and Bootstrap.

### 📷 Screenshots

image

image

image

### CODE REVIEW

**Comment by Astrodevil** [comment]
Your project is not running properly on my side. You have pushed so many unnecessary files. I conveyed the same in previous conversations.  Still, the same files exist here.

One of our mentors asked you if your project has any prerequisites to run on a local machine. Your project is not running properly at my side. You have pushed so many unnecessary files. I convey the same in previous conversations.  Still same files exists here.

**Comment by KiranAminPanjwani** [comment]
Okay, I have finally figured out the problem, give few minutes. i am updating it.

**Comment by KiranAminPanjwani** [comment]
Kindly check it now.

**Comment by KiranAminPanjwani** [comment]
>  

Give me a moment.

**Comment by KiranAminPanjwani** [comment]
> You have pushed some unnecessary files like ds store, extra folders and lots of minify files. may be removing these files will solve the errors. lots of conflicts coming in my local.
> 
> Tell me if your project has any prerequisites to run on a local machine.

No, they don't have any prerequisites. Actually, there are problems with file linking, but I'm fixing them.

**Comment by NOiR-07** [comment]
> @Astrodevil I have fixed all the problems, kindly check it now.✨

it's working fine now, just update your forked repo and resolve the issue in readme (only need to change the project number)

**Comment by NOiR-07** [comment]
> @Astrodevil I have fixed all the problems, kindly check it now.✨

project is now working fine, just update your forked repo and resolve the conflict in readme(just change the project number after updating)

**Pull request merged**
