### PR TITLE
added flappy bird

### PR DESCRIPTION
**Pull request by TsarPrince**
### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
image
image

### CODE REVIEW

**Comment by NOiR-07** [comment]
update your forked repo

**Comment by TsarPrince** [comment]
@NOiR-07 merge conflict resolved, should I change something else?

**Comment by NOiR-07** [comment]
sorry for the delay, there are some changes In the file structure of website so i would suggest you to make the same or push a new pr

**Comment by Astrodevil** [comment]
update your project on cards.json alphabetically and README after updating fork

**Comment by Astrodevil** [comment]
@TsarPrince  You still have time till evening. After that I will be closing this PR.

**Pull request closed without merging**
