### PR TITLE
15-puzzle-Challenge added

### PR DESCRIPTION
**Pull request by Sabarinathan07**
### 👨‍💻 Changes proposed
Adding of 15-puzzle-Challenge

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
The 15 puzzle challenge works completely fine. It doesn't break any part of the project. Tech Stack used: HTML, CSS, Js. I have uploaded the screenshot after adding my project. Please merge my pull request! Thanks!!!

### 📷 Screenshots

Screenshot 2022-04-21 at 5 24 17 PM
Screenshot 2022-04-21 at 5 24 24 PM

### CODE REVIEW

**Comment by Sabarinathan07** [comment]
Please assign it to me for GSSOC'22

**Comment by Sabarinathan07** [comment]
Please add GSSoC22 tag!

**Comment by Astrodevil** [comment]
Also add your project in README

**Comment by Sabarinathan07** [comment]
Added my project in README!!

**Comment by Sabarinathan07** [comment]
Is there any other thing? @Astrodevil

**Pull request merged**
